#include "src/game/envfx_snow.h"

const GeoLayout thwompqueen_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 795, -30, -7, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_torso_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 612, 0, 7, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_head_mesh_layer_1_mat_override_Metal_0),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_larm1_skinned_mesh_layer_1_mat_override_Metal_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 164, 507, -14, 7, 0, -126),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_larm1_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_larm2_skinned_mesh_layer_1_mat_override_Metal_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 234, 0, 0, 0, -3),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_larm2_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 0, 234, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, thwompqueen_lhand_mesh_layer_4_mat_override_Metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_lleg1_skinned_mesh_layer_1_mat_override_Metal_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 88, -41, -84, -2, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_lleg1_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_lleg2_skinned_mesh_layer_1_mat_override_Metal_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 274, 0, -19, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_lleg2_mesh_layer_1_mat_override_Metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rarm1_skinned_mesh_layer_1_mat_override_Metal_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -172, 507, -14, 7, 0, 126),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rarm1_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rarm2_skinned_mesh_layer_1_mat_override_Metal_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 234, 0, 9, 0, 3),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rarm2_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 0, 221, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, thwompqueen_rhand_mesh_layer_4_mat_override_Metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rleg1_skinned_mesh_layer_1_mat_override_Metal_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -96, -41, -84, -2, 0, -180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rleg1_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rleg2_skinned_mesh_layer_1_mat_override_Metal_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 274, 0, -19, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rleg2_mesh_layer_1_mat_override_Metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout thwompqueen_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 795, -30, -7, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 612, 0, 7, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_head_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_larm1_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 164, 507, -14, 7, 0, -126),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_larm1_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_larm2_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 234, 0, 0, 0, -3),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_larm2_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 0, 234, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, thwompqueen_lhand_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_lleg1_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 88, -41, -84, -2, 0, 180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_lleg1_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_lleg2_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 274, 0, -19, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_lleg2_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rarm1_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -172, 507, -14, 7, 0, 126),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rarm1_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rarm2_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 234, 0, 9, 0, 3),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rarm2_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 0, 221, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, thwompqueen_rhand_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rleg1_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -96, -41, -84, -2, 0, -180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rleg1_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_rleg2_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 274, 0, -19, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, thwompqueen_rleg2_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, thwompqueen_switch_opt1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thwompqueen_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thwompqueen_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
