extern const GeoLayout conv2_ccm_geo[];
extern u8 conv2_ccm_FactoryArrow_ci8[];
extern u8 conv2_ccm_FactoryArrow_ci8_pal_rgba16[];
extern Vtx conv2_ccm_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx conv2_ccm_Circle_001_mesh_layer_1_vtx_0[64];
extern Gfx conv2_ccm_Circle_001_mesh_layer_1_tri_0[];
extern Gfx mat_conv2_ccm_Conveyor[];
extern Gfx mat_revert_conv2_ccm_Conveyor[];
extern Gfx conv2_ccm_Circle_001_mesh_layer_1[];
extern Gfx conv2_ccm_material_revert_render_settings[];
