extern const GeoLayout stopsign_geo[];
extern Lights1 stopsign_StopSign_lights;
extern u8 stopsign_rgba16_anonmoose_envmap_silver1_i8[];
extern u8 stopsign_StopSign_ci8[];
extern u8 stopsign_StopSign_ci8_pal_rgba16[];
extern Vtx stopsign_Cube_008_mesh_layer_1_vtx_0[12];
extern Gfx stopsign_Cube_008_mesh_layer_1_tri_0[];
extern Vtx stopsign_Cube_008_mesh_layer_4_vtx_0[8];
extern Gfx stopsign_Cube_008_mesh_layer_4_tri_0[];
extern Gfx mat_stopsign_Funny_envmap[];
extern Gfx mat_revert_stopsign_Funny_envmap[];
extern Gfx mat_stopsign_StopSign[];
extern Gfx mat_revert_stopsign_StopSign[];
extern Gfx stopsign_Cube_008_mesh_layer_1[];
extern Gfx stopsign_Cube_008_mesh_layer_4[];
extern Gfx stopsign_material_revert_render_settings[];
