#include "src/game/envfx_snow.h"

const GeoLayout bowser_no_shadow_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NOP_1A(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_1_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_2_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_3_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_4_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_5_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_6_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_7_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_eye_option_8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_eye_option_8_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_1_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_2_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_3_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_4_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_5_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_6_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_7_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_eye_option_8_face_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_002_opaque_transperant_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 136, 130, NULL),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_face_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_1),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_2),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_3),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_4),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_5),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_6),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_7),
					GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1_jump_bowser_eye_option_8),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, bowser_jaw_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 118, 67, 105, bowser_left_arm_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, bowser_left_elbow_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, bowser_left_hand_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -2, -18, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, bowser_left_knee_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, bowser_left_feet_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, -118, 67, 105, bowser_right_arm_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, bowser_right_elbow_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, bowser_right_hand_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -2, -18, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, bowser_right_knee_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, bowser_right_feet_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -32, -112, bowser_tail_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_body_rot_from_parent),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ASM(0, geo_bowser_revert_rendermode),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_geo[] = {
	GEO_CULLING_RADIUS(740),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(2, geo_disable_or_enable_bowser_shadow),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_SHADOW(0, 155, 400),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, bowser_no_shadow_option),
			GEO_CLOSE_NODE(),
			GEO_ASM(0, geo_bowser_transparency_and_rainbow),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_root_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 136, 130, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_face_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, bowser_eye_option_1),
								GEO_BRANCH(1, bowser_eye_option_2),
								GEO_BRANCH(1, bowser_eye_option_3),
								GEO_BRANCH(1, bowser_eye_option_4),
								GEO_BRANCH(1, bowser_eye_option_5),
								GEO_BRANCH(1, bowser_eye_option_6),
								GEO_BRANCH(1, bowser_eye_option_7),
								GEO_BRANCH(1, bowser_eye_option_8),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, bowser_jaw_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 118, 67, 105, bowser_left_arm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, bowser_left_elbow_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, bowser_left_hand_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -2, -18, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, bowser_left_knee_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, bowser_left_feet_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -118, 67, 105, bowser_right_arm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, bowser_right_elbow_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, bowser_right_hand_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -2, -18, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, bowser_right_knee_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, bowser_right_feet_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -32, -112, bowser_tail_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_update_body_rot_from_parent),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, bowser_002_opaque_transperant_switch_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
