extern const GeoLayout corenode_geo[];
extern Lights1 corenode_f3d_material_lights;
extern u8 corenode_core_ci8[];
extern u8 corenode_core_ci8_pal_rgba16[];
extern Vtx corenode_Plane_004_mesh_layer_4_vtx_cull[8];
extern Vtx corenode_Plane_004_mesh_layer_4_vtx_0[4];
extern Gfx corenode_Plane_004_mesh_layer_4_tri_0[];
extern Gfx mat_corenode_f3d_material[];
extern Gfx mat_revert_corenode_f3d_material[];
extern Gfx corenode_Plane_004_mesh_layer_4[];
extern Gfx corenode_material_revert_render_settings[];
