extern const GeoLayout spooner_geo[];
extern Lights1 spooner_side_lights;
extern Lights1 spooner_flamethrower_hole_lights;
extern u8 spooner_Glover_600021FC_0_0_468B1659_ciByRGBA_ci8[];
extern u8 spooner_Glover_600021FC_0_0_468B1659_ciByRGBA_pal_rgba16[];
extern u8 spooner_Flamethrower_Hole_ci8[];
extern u8 spooner_Flamethrower_Hole_pal_rgba16[];
extern Vtx spooner_FireSpinner_mesh_layer_1_vtx_0[70];
extern Gfx spooner_FireSpinner_mesh_layer_1_tri_0[];
extern Vtx spooner_FireSpinner_mesh_layer_4_vtx_0[8];
extern Gfx spooner_FireSpinner_mesh_layer_4_tri_0[];
extern Gfx mat_spooner_side[];
extern Gfx mat_revert_spooner_side[];
extern Gfx mat_spooner_flamethrower_hole[];
extern Gfx mat_revert_spooner_flamethrower_hole[];
extern Gfx spooner_FireSpinner_mesh_layer_1[];
extern Gfx spooner_FireSpinner_mesh_layer_4[];
