#include "src/game/envfx_snow.h"

const GeoLayout bitfs_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_Cube_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_Cube_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitfs_dl_Cube_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_Cube_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_Cube_005_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7223, -792, -10202, bitfs_dl_Cube_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_Cube_009_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_Cube_012_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_Cube_013_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_Cube_014_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_Cube_014_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitfs_dl_decor_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_decor_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -7223, -377, -7562, 90, 0, 180, bitfs_dl_ShowrunnerStatue_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7607, -5304, -52, bitfs_dl_ShowrunnerStatue_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_visual_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitfs_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x214F),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bitfs_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitfs_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitfs_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitfs_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
