extern const GeoLayout blood_particle_geo[];
extern Lights1 blood_particle_blood_lights;
extern u8 blood_particle_Blood_i8[];
extern Vtx blood_particle_Cube_009_mesh_layer_5_vtx_cull[8];
extern Vtx blood_particle_Cube_009_mesh_layer_5_vtx_0[14];
extern Gfx blood_particle_Cube_009_mesh_layer_5_tri_0[];
extern Gfx mat_blood_particle_blood[];
extern Gfx mat_revert_blood_particle_blood[];
extern Gfx blood_particle_Cube_009_mesh_layer_5[];
extern Gfx blood_particle_material_revert_render_settings[];
