extern const GeoLayout rockplate_geo[];
extern Lights1 rockplate_goku_lights;
extern u8 rockplate_gokaku_ci8[];
extern u8 rockplate_gokaku_ci8_pal_rgba16[];
extern Vtx rockplate_Cube_001_mesh_layer_1_vtx_0[29];
extern Gfx rockplate_Cube_001_mesh_layer_1_tri_0[];
extern Gfx mat_rockplate_goku[];
extern Gfx mat_revert_rockplate_goku[];
extern Gfx rockplate_Cube_001_mesh_layer_1[];
extern Gfx rockplate_material_revert_render_settings[];
