extern const GeoLayout agmoon_geo[];
extern Lights1 agmoon__3D_Agamemnon_lights;
extern u8 agmoon__3D_Agamemnon_Texture_i8[];
extern u8 agmoon_Static2_i8[];
extern u8 agmoon_Eye_i8[];
extern Vtx agmoon_Sphere_002_mesh_layer_1_vtx_cull[8];
extern Vtx agmoon_Sphere_002_mesh_layer_1_vtx_0[233];
extern Gfx agmoon_Sphere_002_mesh_layer_1_tri_0[];
extern Vtx agmoon_Sphere_002_mesh_layer_1_vtx_1[36];
extern Gfx agmoon_Sphere_002_mesh_layer_1_tri_1[];
extern Gfx mat_agmoon__3D_Agamemnon[];
extern Gfx mat_agmoon_Static_layer1[];
extern Gfx mat_revert_agmoon_Static_layer1[];
extern Gfx agmoon_Sphere_002_mesh_layer_1[];
extern Gfx agmoon_material_revert_render_settings[];
