extern const GeoLayout rbowser_Material_opt1[];
extern const GeoLayout rbowser_Material_opt2[];
extern const GeoLayout rbowser_Material_opt3[];
extern const GeoLayout rbowser_geo[];
extern u8 rbowser_Bowser_Idle_ci4[];
extern u8 rbowser_Bowser_Idle_ci4_pal_rgba16[];
extern u8 rbowser_Bowser_Hop_ci4[];
extern u8 rbowser_Bowser_Hop_ci4_pal_rgba16[];
extern u8 rbowser_Bowser_Blow_ci4[];
extern u8 rbowser_Bowser_Blow_ci4_pal_rgba16[];
extern u8 rbowser_Bowser_Crush_ci4[];
extern u8 rbowser_Bowser_Crush_ci4_pal_rgba16[];
extern Vtx rbowser_Bowser_mesh_layer_4_vtx_0[4];
extern Gfx rbowser_Bowser_mesh_layer_4_tri_0[];
extern Gfx mat_rbowser_bowser_idle[];
extern Gfx mat_revert_rbowser_bowser_idle[];
extern Gfx mat_rbowser_bowser_hop[];
extern Gfx mat_revert_rbowser_bowser_hop[];
extern Gfx mat_rbowser_bowser_blow[];
extern Gfx mat_revert_rbowser_bowser_blow[];
extern Gfx mat_rbowser_bowser_jump[];
extern Gfx mat_revert_rbowser_bowser_jump[];
extern Gfx rbowser_Bowser_mesh_layer_4[];
extern Gfx rbowser_Bowser_mesh_layer_4_mat_override_bowser_hop_0[];
extern Gfx rbowser_Bowser_mesh_layer_4_mat_override_bowser_blow_1[];
extern Gfx rbowser_Bowser_mesh_layer_4_mat_override_bowser_jump_2[];
extern Gfx rbowser_material_revert_render_settings[];
