extern const GeoLayout ladybug_geo[];
extern u8 ladybug_LadyBug_ci4[];
extern u8 ladybug_LadyBug_ci4_pal_rgba16[];
extern Vtx ladybug_Plane_009_mesh_layer_4_vtx_cull[8];
extern Vtx ladybug_Plane_009_mesh_layer_4_vtx_0[4];
extern Gfx ladybug_Plane_009_mesh_layer_4_tri_0[];
extern Gfx mat_ladybug_Ladybug[];
extern Gfx mat_revert_ladybug_Ladybug[];
extern Gfx ladybug_Plane_009_mesh_layer_4[];
extern Gfx ladybug_material_revert_render_settings[];
