extern const GeoLayout imbues_geo[];
extern Vtx imbues_imbue_star_mesh_layer_7_vtx_0[18];
extern Gfx imbues_imbue_star_mesh_layer_7_tri_0[];
extern Vtx imbues_imbue_star_mesh_layer_7_vtx_1[28];
extern Gfx imbues_imbue_star_mesh_layer_7_tri_1[];
extern Gfx mat_imbues_noz_dynamic[];
extern Gfx mat_revert_imbues_noz_dynamic[];
extern Gfx mat_imbues_noz_black[];
extern Gfx mat_revert_imbues_noz_black[];
extern Gfx imbues_imbue_star_mesh_layer_7[];
