extern const GeoLayout imbues_geo[];
extern Vtx imbues_imbue_star_mesh_layer_7_vtx_0[22];
extern Gfx imbues_imbue_star_mesh_layer_7_tri_0[];
extern Vtx imbues_imbue_star_mesh_layer_7_vtx_1[24];
extern Gfx imbues_imbue_star_mesh_layer_7_tri_1[];
extern Vtx imbues_imbue_star_mesh_layer_7_vtx_2[10];
extern Gfx imbues_imbue_star_mesh_layer_7_tri_2[];
extern Gfx mat_imbues_noz_red[];
extern Gfx mat_revert_imbues_noz_red[];
extern Gfx mat_imbues_noz_black[];
extern Gfx mat_revert_imbues_noz_black[];
extern Gfx mat_imbues_noz_white[];
extern Gfx mat_revert_imbues_noz_white[];
extern Gfx imbues_imbue_star_mesh_layer_7[];
extern Gfx imbues_material_revert_render_settings[];
