#include "src/game/envfx_snow.h"

const GeoLayout banner_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, banner_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, banner_flap1_skinned_mesh_layer_4),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 504, 57, -180, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, banner_flap1_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, banner_flap2_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 111, 0, banner_flap2_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, banner_flap3_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 111, 0, banner_flap3_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, banner_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, banner_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
