extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const MacroObject castle_courtyard_area_1_macro_objs[];
extern const GeoLayout castle_courtyard_area_2_geo[];
extern const GeoLayout castle_courtyard_area_2[];
extern const Collision castle_courtyard_area_2_collision[];
extern const MacroObject castle_courtyard_area_2_macro_objs[];
extern const GeoLayout castle_courtyard_area_3_geo[];
extern const GeoLayout castle_courtyard_area_3[];
extern const Collision castle_courtyard_area_3_collision[];
extern const MacroObject castle_courtyard_area_3_macro_objs[];
extern const GeoLayout castle_courtyard_area_4_geo[];
extern const GeoLayout castle_courtyard_area_4[];
extern const Collision castle_courtyard_area_4_collision[];
extern const MacroObject castle_courtyard_area_4_macro_objs[];
extern Lights1 castle_courtyard_dl_f3d_material_lights;
extern Lights1 castle_courtyard_dl_Carpet_lights;
extern Lights1 castle_courtyard_dl_Floor_lights;
extern u8 castle_courtyard_dl_night_mt_ci8[];
extern u8 castle_courtyard_dl_night_mt_ci8_pal_rgba16[];
extern u8 castle_courtyard_dl_carpet2_ci4[];
extern u8 castle_courtyard_dl_carpet2_ci4_pal_rgba16[];
extern u8 castle_courtyard_dl_gate_ci8[];
extern u8 castle_courtyard_dl_gate_ci8_pal_rgba16[];
extern u8 castle_courtyard_dl_output_0_custom_i8_ia8[];
extern u8 castle_courtyard_dl_Ground_ci4[];
extern u8 castle_courtyard_dl_Ground_ci4_pal_rgba16[];
extern u8 castle_courtyard_dl_Back_graund_rgba16[];
extern Vtx castle_courtyard_dl_vis_mesh_layer_1_vtx_0[16];
extern Gfx castle_courtyard_dl_vis_mesh_layer_1_tri_0[];
extern Vtx castle_courtyard_dl_vis_mesh_layer_1_vtx_1[4];
extern Gfx castle_courtyard_dl_vis_mesh_layer_1_tri_1[];
extern Vtx castle_courtyard_dl_vis_mesh_layer_1_vtx_2[12];
extern Gfx castle_courtyard_dl_vis_mesh_layer_1_tri_2[];
extern Vtx castle_courtyard_dl_vis_001_mesh_layer_1_vtx_0[56];
extern Gfx castle_courtyard_dl_vis_001_mesh_layer_1_tri_0[];
extern Vtx castle_courtyard_dl_vis_001_mesh_layer_1_vtx_1[14];
extern Gfx castle_courtyard_dl_vis_001_mesh_layer_1_tri_1[];
extern Vtx castle_courtyard_dl_vis_001_mesh_layer_1_vtx_2[14];
extern Gfx castle_courtyard_dl_vis_001_mesh_layer_1_tri_2[];
extern Vtx castle_courtyard_dl_Cube_mesh_layer_1_vtx_0[16];
extern Gfx castle_courtyard_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_courtyard_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx castle_courtyard_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx castle_courtyard_dl_Cube_mesh_layer_1_vtx_2[4];
extern Gfx castle_courtyard_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx castle_courtyard_dl_Cube_001_mesh_layer_1_vtx_0[8];
extern Gfx castle_courtyard_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx castle_courtyard_dl_Cube_001_mesh_layer_1_vtx_1[90];
extern Gfx castle_courtyard_dl_Cube_001_mesh_layer_1_tri_1[];
extern Gfx mat_castle_courtyard_dl_f3d_material[];
extern Gfx mat_revert_castle_courtyard_dl_f3d_material[];
extern Gfx mat_castle_courtyard_dl_Carpet[];
extern Gfx mat_revert_castle_courtyard_dl_Carpet[];
extern Gfx mat_castle_courtyard_dl_Floor[];
extern Gfx mat_revert_castle_courtyard_dl_Floor[];
extern Gfx mat_castle_courtyard_dl_badder_apple[];
extern Gfx mat_castle_courtyard_dl_Ground[];
extern Gfx mat_revert_castle_courtyard_dl_Ground[];
extern Gfx mat_castle_courtyard_dl_BG[];
extern Gfx mat_revert_castle_courtyard_dl_BG[];
extern Gfx castle_courtyard_dl_vis_mesh_layer_1[];
extern Gfx castle_courtyard_dl_vis_001_mesh_layer_1[];
extern Gfx castle_courtyard_dl_Cube_mesh_layer_1[];
extern Gfx castle_courtyard_dl_Cube_001_mesh_layer_1[];
extern Gfx castle_courtyard_dl_material_revert_render_settings[];
