extern const GeoLayout bowser_bomb_geo[];
extern Lights1 bomb_spikes_lights;
extern u8 bomb_bomb_spike_rgba16_rgba16[];
extern u8 bomb_bomb_left_side_rgba16_rgba16[];
extern u8 bomb_bomb_right_side_rgba16_rgba16[];
extern Vtx bomb_spikes_mesh_layer_1_vtx_0[55];
extern Vtx bomb_bomb_billboard_mesh_layer_4_vtx_0[4];
extern Vtx bomb_bomb_billboard_mesh_layer_4_vtx_1[4];
extern Gfx bomb_spikes_mesh_layer_1[];
extern Gfx bomb_bomb_billboard_mesh_layer_4[];
extern Gfx bomb_material_revert_render_settings[];
