COURSE_ACTS(COURSE_BOB, _(" 1 BATAILLE DE BOB-OMB"),
       _("ROI BOB-OMB DU SOMMET")         , _("COURSE CONTRE KOOPA-RAPIDO")    , _("CANON VERS L'ILE PERCHEE"),
       _("LES 8 PIECES ROUGES")           , _("VOL DU MARIO AILE")             , _("DERRIERE LA CAGE DE CHOMP"))

CASTLE_SECRET_STARS(_("   ETOILES SECRETES"))

EXTRA_TEXT(0, _("UNE ETOILE SECRETE DU CHATEAU"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
