#pragma once

#include "mb64/gfx/tile.h"

// Terrain
extern const struct texture_define mb64_tex_Grass;
extern const struct texture_define mb64_tex_GrassSide;
extern const struct texture_define mb64_tex_VanillaGrass;
extern const struct texture_define mb64_tex_CartoonGrass;
extern const struct texture_define mb64_tex_CartoonGrassSide;
extern const struct texture_define mb64_tex_DarkGrass;
extern const struct texture_define mb64_tex_DarkGrassSide;
extern const struct texture_define mb64_tex_HGrass;
extern const struct texture_define mb64_tex_HGrassSide;
extern const struct texture_define mb64_tex_OrangeGrass;
extern const struct texture_define mb64_tex_OrangeGrassSide;
extern const struct texture_define mb64_tex_RedGrass;
extern const struct texture_define mb64_tex_RedGrassSide;
extern const struct texture_define mb64_tex_PurpleGrass;
extern const struct texture_define mb64_tex_PurpleGrassSide;
extern const struct texture_define mb64_tex_Sand;
extern const struct texture_define mb64_tex_SandSide;
extern const struct texture_define mb64_tex_JRBSand;
extern const struct texture_define mb64_tex_Snow;
extern const struct texture_define mb64_tex_SnowSide;
extern const struct texture_define mb64_tex_VanillaSnow;
extern const struct texture_define mb64_tex_Dirt;
extern const struct texture_define mb64_tex_SandDirt;
extern const struct texture_define mb64_tex_LightDirt;
extern const struct texture_define mb64_tex_HDirt;
extern const struct texture_define mb64_tex_RockyDirt;
extern const struct texture_define mb64_tex_VanillaDirt;
extern const struct texture_define mb64_tex_WavyDirt;
extern const struct texture_define mb64_tex_WavyDirtBlue;
extern const struct texture_define mb64_tex_SnowDirt;
extern const struct texture_define mb64_tex_PurpleDirt;
extern const struct texture_define mb64_tex_HLakewall;
// Stone
extern const struct texture_define mb64_tex_StoneSide;
extern const struct texture_define mb64_tex_HStone;
extern const struct texture_define mb64_tex_HMazefloor;
extern const struct texture_define mb64_tex_CCMWall;
extern const struct texture_define mb64_tex_MountainFloor;
extern const struct texture_define mb64_tex_MountainRock;
extern const struct texture_define mb64_tex_Stone;
extern const struct texture_define mb64_tex_JRBWall;
extern const struct texture_define mb64_tex_BlackStone;
extern const struct texture_define mb64_tex_RHRStone;
extern const struct texture_define mb64_tex_LavaRock;
extern const struct texture_define mb64_tex_LavaRockEdge;
extern const struct texture_define mb64_tex_VolcanicRock;
extern const struct texture_define mb64_tex_RHRBasalt;
extern const struct texture_define mb64_tex_Obsidian;
extern const struct texture_define mb64_tex_CastleCobble;
extern const struct texture_define mb64_tex_JRBUnderwater;
extern const struct texture_define mb64_tex_SnowRock;
extern const struct texture_define mb64_tex_IcyRock;
extern const struct texture_define mb64_tex_DStone;
extern const struct texture_define mb64_tex_RHRObsidian;
extern const struct texture_define mb64_tex_JRBStone;
// Bricks
extern const struct texture_define mb64_tex_Bricks;
extern const struct texture_define mb64_tex_DBrick;
extern const struct texture_define mb64_tex_RHRBrick;
extern const struct texture_define mb64_tex_HBrick;
extern const struct texture_define mb64_tex_LightBrownBricks;
extern const struct texture_define mb64_tex_BrownBricks;
extern const struct texture_define mb64_tex_TTMBricks;
extern const struct texture_define mb64_tex_CBrick;
extern const struct texture_define mb64_tex_BBHBricks;
extern const struct texture_define mb64_tex_RoofBricks;
extern const struct texture_define mb64_tex_COutsideBricks;
extern const struct texture_define mb64_tex_SnowBricks;
extern const struct texture_define mb64_tex_JRBBricks;
extern const struct texture_define mb64_tex_SnowTileSide;
extern const struct texture_define mb64_tex_TileBricks;
// Tiling
extern const struct texture_define mb64_tex_Tiles;
extern const struct texture_define mb64_tex_TileEdge;
extern const struct texture_define mb64_tex_CTiles;
extern const struct texture_define mb64_tex_DTiles;
extern const struct texture_define mb64_tex_VBlueTiles;
extern const struct texture_define mb64_tex_SnowTiles;
extern const struct texture_define mb64_tex_SnowTileRim;
extern const struct texture_define mb64_tex_JRBTileTop;
extern const struct texture_define mb64_tex_JRBTileRim;
extern const struct texture_define mb64_tex_JRBTileSide;
extern const struct texture_define mb64_tex_HTileTop;
extern const struct texture_define mb64_tex_GraniteTiles;
extern const struct texture_define mb64_tex_RHRTiles;
extern const struct texture_define mb64_tex_VTiles;
extern const struct texture_define mb64_tex_DiamondPattern;
extern const struct texture_define mb64_tex_CStone;
extern const struct texture_define mb64_tex_CastleHexRim;
extern const struct texture_define mb64_tex_SnowBrickTiles;
// Cut Stone
extern const struct texture_define mb64_tex_DStoneBlock;
extern const struct texture_define mb64_tex_VBlock;
extern const struct texture_define mb64_tex_BBHWall;
extern const struct texture_define mb64_tex_BBHMetalSide;
extern const struct texture_define mb64_tex_BBHStonePattern;
extern const struct texture_define mb64_tex_LauncherTex;
extern const struct texture_define mb64_tex_HTileSide;
extern const struct texture_define mb64_tex_RHRPattern;
extern const struct texture_define mb64_tex_GraniteBlock;
extern const struct texture_define mb64_tex_CStoneSide;
extern const struct texture_define mb64_tex_CPillar;
extern const struct texture_define mb64_tex_BBHPillar;
extern const struct texture_define mb64_tex_RHRPillar;
// Wood
extern const struct texture_define mb64_tex_Wood;
extern const struct texture_define mb64_tex_BBHWoodWall;
extern const struct texture_define mb64_tex_BBHWoodFloor;
extern const struct texture_define mb64_tex_CWood;
extern const struct texture_define mb64_tex_JRBWood;
extern const struct texture_define mb64_tex_JRBShipSide;
extern const struct texture_define mb64_tex_JRBShipTop;
extern const struct texture_define mb64_tex_BBHHauntedPlanks;
extern const struct texture_define mb64_tex_BBHRoof;
extern const struct texture_define mb64_tex_SolidWood;
extern const struct texture_define mb64_tex_RHRWood;
// Metal
extern const struct texture_define mb64_tex_BBHMetal;
extern const struct texture_define mb64_tex_JRBMetalSide;
extern const struct texture_define mb64_tex_JRBMetal;
extern const struct texture_define mb64_tex_CBasementWall;
extern const struct texture_define mb64_tex_DTiles2;
extern const struct texture_define mb64_tex_VRustyBlock;
// Other
extern const struct texture_define mb64_tex_CCarpet;
extern const struct texture_define mb64_tex_CWall;
extern const struct texture_define mb64_tex_Roof;
extern const struct texture_define mb64_tex_CRoof;
extern const struct texture_define mb64_tex_SnowRoof;
extern const struct texture_define mb64_tex_BBHWindow;
extern const struct texture_define mb64_tex_HLight;
extern const struct texture_define mb64_tex_Caution;
extern const struct texture_define mb64_tex_RRBlocks;
extern const struct texture_define mb64_tex_StuddedFloor;
extern const struct texture_define mb64_tex_YellowBlock;
extern const struct texture_define mb64_tex_TTCSide;
extern const struct texture_define mb64_tex_TTCWall;
extern const struct texture_define mb64_tex_FlowerTop;
extern const struct texture_define mb64_tex_FlowerEdge;
// Hazards
extern const struct texture_define mb64_tex_Lava;
extern const struct texture_define mb64_tex_VanillaLava;
extern const struct texture_define mb64_tex_ServerAcid;
extern const struct texture_define mb64_tex_BurningIce;
extern const struct texture_define mb64_tex_Quicksand;
extern const struct texture_define mb64_tex_Slowsand;
extern const struct texture_define mb64_tex_Void;
// Transparent
extern const struct texture_define mb64_tex_RHRMesh;
extern const struct texture_define mb64_tex_VPMesh;
extern const struct texture_define mb64_tex_HMesh;
extern const struct texture_define mb64_tex_BBHMesh;
extern const struct texture_define mb64_tex_GratePink;
extern const struct texture_define mb64_tex_TTCGrate;
extern const struct texture_define mb64_tex_Ice;
extern const struct texture_define mb64_tex_Crystal;
extern const struct texture_define mb64_tex_Screen;
// Retro
extern const struct texture_define mb64_tex_RetroGround;
extern const struct texture_define mb64_tex_RetroBrick;
extern const struct texture_define mb64_tex_RetroTreeTop;
extern const struct texture_define mb64_tex_RetroTreeSide;
extern const struct texture_define mb64_tex_RetroTree;
extern const struct texture_define mb64_tex_RetroBlock;
extern const struct texture_define mb64_tex_RetroBGround;
extern const struct texture_define mb64_tex_RetroBBrick;
extern const struct texture_define mb64_tex_RetroBBlock;
extern const struct texture_define mb64_tex_RetroWBrick;
extern const struct texture_define mb64_tex_RetroLava;
extern const struct texture_define mb64_tex_RetroUnderwater;
// Minecraft
extern const struct texture_define mb64_tex_MCDirt;
extern const struct texture_define mb64_tex_MCGrassTop;
extern const struct texture_define mb64_tex_MCGrassEdge;
extern const struct texture_define mb64_tex_MCCobblestone;
extern const struct texture_define mb64_tex_MCStone;
extern const struct texture_define mb64_tex_MCOakLogTop;
extern const struct texture_define mb64_tex_MCOakLogSide;
extern const struct texture_define mb64_tex_MCOakLeaves;
extern const struct texture_define mb64_tex_MCWoodPlanks;
extern const struct texture_define mb64_tex_MCSand;
extern const struct texture_define mb64_tex_MCBricks;
extern const struct texture_define mb64_tex_MCLava;
extern const struct texture_define mb64_tex_MCFlowingLava;
extern const struct texture_define mb64_tex_MCGlass;
// Fences
extern const struct texture_define mb64_tex_Fence;
extern const struct texture_define mb64_tex_WoodenFence;
extern const struct texture_define mb64_tex_DFence;
extern const struct texture_define mb64_tex_BarbedWire;
extern const struct texture_define mb64_tex_RHRFence;
extern const struct texture_define mb64_tex_HFence;
extern const struct texture_define mb64_tex_CFence;
extern const struct texture_define mb64_tex_VPFence;
extern const struct texture_define mb64_tex_BBHFence;
extern const struct texture_define mb64_tex_JRBFence;
extern const struct texture_define mb64_tex_SnowFence2;
extern const struct texture_define mb64_tex_SnowFence;
extern const struct texture_define mb64_tex_RetroFence;
extern const struct texture_define mb64_tex_MCFence;
// Bars
extern const struct texture_define mb64_tex_IronBars;
extern const struct texture_define mb64_tex_IronBarsTop;
extern const struct texture_define mb64_tex_ChainTop;
extern const struct texture_define mb64_tex_HMCTop;
extern const struct texture_define mb64_tex_ChainTopPink;
extern const struct texture_define mb64_tex_TTCGrateTop;
extern const struct texture_define mb64_tex_DMesh;
extern const struct texture_define mb64_tex_DesertMeshTop;
extern const struct texture_define mb64_tex_BOBBars;
extern const struct texture_define mb64_tex_BOBBarsTop;
extern const struct texture_define mb64_tex_RetroMesh;
extern const struct texture_define mb64_tex_RetroMeshTop;
extern const struct texture_define mb64_tex_MCIronBars;
extern const struct texture_define mb64_tex_MCIronBarsTop;
// Water
extern const struct texture_define mb64_tex_Water;
extern const struct texture_define mb64_tex_GreenWater;
extern const struct texture_define mb64_tex_RetroWater;
extern const struct texture_define mb64_tex_MCWater;

extern const Gfx mb64_dl_Black[];

void scroll_mb64_textures(void);
