extern const GeoLayout smashbrick_geo[];
extern u8 smashbrick_BreakableBrick_ci4[];
extern u8 smashbrick_BreakableBrick_ci4_pal_rgba16[];
extern Vtx smashbrick_Cube_005_mesh_layer_1_vtx_cull[8];
extern Vtx smashbrick_Cube_005_mesh_layer_1_vtx_0[4];
extern Gfx smashbrick_Cube_005_mesh_layer_1_tri_0[];
extern Gfx mat_smashbrick_Breakable[];
extern Gfx mat_revert_smashbrick_Breakable[];
extern Gfx smashbrick_Cube_005_mesh_layer_1[];
extern Gfx smashbrick_material_revert_render_settings[];
