extern const GeoLayout star_sign_geo[];
extern Lights1 star_sign_signage2_lights;
extern u8 star_sign_Signage2_ci8[];
extern u8 star_sign_Signage2_ci8_pal_rgba16[];
extern u8 star_sign_Signage_rgba16[];
extern Vtx star_sign_Cube_017_mesh_layer_1_vtx_0[40];
extern Gfx star_sign_Cube_017_mesh_layer_1_tri_0[];
extern Vtx star_sign_Cube_017_mesh_layer_4_vtx_0[8];
extern Gfx star_sign_Cube_017_mesh_layer_4_tri_0[];
extern Gfx mat_star_sign_signage2[];
extern Gfx mat_revert_star_sign_signage2[];
extern Gfx mat_star_sign_signage21[];
extern Gfx star_sign_Cube_017_mesh_layer_1[];
extern Gfx star_sign_Cube_017_mesh_layer_4[];
extern Gfx star_sign_material_revert_render_settings[];
