extern const GeoLayout snakeblock1_Smaller[];
extern const GeoLayout snakeblock1_Armature[];
extern const GeoLayout snakeblock1_geo[];
extern Lights1 snakeblock1_SnakeBlock2_lights;
extern Lights1 snakeblock1_snakeblock1_lights;
extern Lights1 snakeblock1_cursedblock2_lights;
extern u8 snakeblock1_SnakeBlock2_ci8[];
extern u8 snakeblock1_SnakeBlock2_ci8_pal_rgba16[];
extern u8 snakeblock1_CursedSnakeBlock_ci8[];
extern u8 snakeblock1_CursedSnakeBlock_ci8_pal_rgba16[];
extern u8 snakeblock1_newnsake_ci8[];
extern u8 snakeblock1_newnsake_ci8_pal_rgba16[];
extern Vtx snakeblock1_Block_mesh_layer_1_vtx_0[8];
extern Gfx snakeblock1_Block_mesh_layer_1_tri_0[];
extern Vtx snakeblock1_Block_mesh_layer_1_vtx_1[16];
extern Gfx snakeblock1_Block_mesh_layer_1_tri_1[];
extern Vtx snakeblock1_switch_option_Block3_mesh_layer_1_vtx_0[8];
extern Gfx snakeblock1_switch_option_Block3_mesh_layer_1_tri_0[];
extern Vtx snakeblock1_switch_option_Block3_mesh_layer_1_vtx_1[16];
extern Gfx snakeblock1_switch_option_Block3_mesh_layer_1_tri_1[];
extern Vtx snakeblock1_switch_option_Block2_mesh_layer_1_vtx_0[24];
extern Gfx snakeblock1_switch_option_Block2_mesh_layer_1_tri_0[];
extern Vtx snakeblock1_switch_option_Block2_mesh_layer_1_vtx_1[24];
extern Gfx snakeblock1_switch_option_Block2_mesh_layer_1_tri_1[];
extern Vtx snakeblock1_switch_option_Block2_mesh_layer_1_vtx_2[8];
extern Gfx snakeblock1_switch_option_Block2_mesh_layer_1_tri_2[];
extern Gfx mat_snakeblock1_SnakeBlock2[];
extern Gfx mat_revert_snakeblock1_SnakeBlock2[];
extern Gfx mat_snakeblock1_snakeblock1[];
extern Gfx mat_revert_snakeblock1_snakeblock1[];
extern Gfx mat_snakeblock1_cursedblock2[];
extern Gfx mat_revert_snakeblock1_cursedblock2[];
extern Gfx snakeblock1_Block_mesh_layer_1[];
extern Gfx snakeblock1_switch_option_Block3_mesh_layer_1[];
extern Gfx snakeblock1_switch_option_Block2_mesh_layer_1[];
extern Gfx snakeblock1_material_revert_render_settings[];
