extern const GeoLayout cobie_switch_opt1[];
extern const GeoLayout cobie_switch_opt2[];
extern const GeoLayout cobie_geo[];
extern Lights1 cobie_Cobie_Good_lights;
extern Lights1 cobie_Cobie_Bad_lights;
extern u8 cobie_Cobie_Good_ci8[];
extern u8 cobie_Cobie_Good_ci8_pal_rgba16[];
extern u8 cobie_Cobie_Bad_ci8[];
extern u8 cobie_Cobie_Bad_ci8_pal_rgba16[];
extern u8 cobie_cobie_metal_rgba16[];
extern Vtx cobie_root_mesh_layer_1_vtx_0[123];
extern Gfx cobie_root_mesh_layer_1_tri_0[];
extern Vtx cobie_gun_mesh_layer_1_vtx_0[46];
extern Gfx cobie_gun_mesh_layer_1_tri_0[];
extern Vtx cobie_lfoot_mesh_layer_1_vtx_0[14];
extern Gfx cobie_lfoot_mesh_layer_1_tri_0[];
extern Vtx cobie_rfoot_mesh_layer_1_vtx_0[14];
extern Gfx cobie_rfoot_mesh_layer_1_tri_0[];
extern Gfx mat_cobie_Cobie_Good[];
extern Gfx mat_revert_cobie_Cobie_Good[];
extern Gfx mat_cobie_Cobie_Bad[];
extern Gfx mat_revert_cobie_Cobie_Bad[];
extern Gfx mat_cobie_Void[];
extern Gfx mat_revert_cobie_Void[];
extern Gfx cobie_root_mesh_layer_1[];
extern Gfx cobie_root_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie_root_mesh_layer_1_mat_override_Void_1[];
extern Gfx cobie_gun_mesh_layer_1[];
extern Gfx cobie_gun_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie_gun_mesh_layer_1_mat_override_Void_1[];
extern Gfx cobie_lfoot_mesh_layer_1[];
extern Gfx cobie_lfoot_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie_lfoot_mesh_layer_1_mat_override_Void_1[];
extern Gfx cobie_rfoot_mesh_layer_1[];
extern Gfx cobie_rfoot_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie_rfoot_mesh_layer_1_mat_override_Void_1[];
extern Gfx cobie_material_revert_render_settings[];
