extern const GeoLayout msbox_geo[];
extern Lights1 msbox_musicbox_lights;
extern u8 msbox_musicbox_ci8[];
extern u8 msbox_musicbox_ci8_pal_rgba16[];
extern Vtx msbox_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx msbox_Cube_003_mesh_layer_1_vtx_0[62];
extern Gfx msbox_Cube_003_mesh_layer_1_tri_0[];
extern Gfx mat_msbox_musicbox[];
extern Gfx mat_revert_msbox_musicbox[];
extern Gfx msbox_Cube_003_mesh_layer_1[];
extern Gfx msbox_material_revert_render_settings[];
