extern const GeoLayout tankie_geo[];
extern Lights1 tankie_oil_tanker_lights;
extern u8 tankie_oil_tank_ci8[];
extern u8 tankie_oil_tank_ci8_pal_rgba16[];
extern Vtx tankie_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx tankie_Cylinder_001_mesh_layer_1_vtx_0[37];
extern Gfx tankie_Cylinder_001_mesh_layer_1_tri_0[];
extern Gfx mat_tankie_oil_tanker[];
extern Gfx mat_revert_tankie_oil_tanker[];
extern Gfx tankie_Cylinder_001_mesh_layer_1[];
extern Gfx tankie_material_revert_render_settings[];
