extern const GeoLayout hammer_geo[];
extern Lights1 hammer_Handle_001_lights;
extern Lights1 hammer_Hard_001_lights;
extern Vtx hammer_Cylinder_mesh_layer_1_vtx_0[11];
extern Gfx hammer_Cylinder_mesh_layer_1_tri_0[];
extern Vtx hammer_Cylinder_mesh_layer_1_vtx_1[26];
extern Gfx hammer_Cylinder_mesh_layer_1_tri_1[];
extern Gfx mat_hammer_Handle_001[];
extern Gfx mat_hammer_Hard_001[];
extern Gfx hammer_Cylinder_mesh_layer_1[];
extern Gfx hammer_material_revert_render_settings[];
