COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMBS BOMBENBERG"),
       _("BESIEGE KÖNIG BOB-OMB!")        , _("BESIEGE DEN SCHNELLEN KOOPA!")  , _("FLIEGE ZUR SCHWEBENDEN INSEL!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("DURCHFLIEGE ALLE MÜNZENRINGE!") , _("BEFREIE DEN KETTENHUND!"))

CASTLE_SECRET_STARS(_("   GEHEIME STERNE"))

EXTRA_TEXT(0, _("EIN GEHEIMER STERN DES SCHLOSSES!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
