#include "anim_Stand up.inc.c"
#include "anim_Shaking.inc.c"
#include "anim_Grabbed.inc.c"
#include "anim_Broken.inc.c"
#include "anim_Fall down.inc.c"
#include "anim_Fire breath.inc.c"
#include "anim_Jump.inc.c"
#include "anim_Jump stop.inc.c"
#include "anim_Jump start.inc.c"
#include "anim_Dance.inc.c"
#include "anim_Fire breath up.inc.c"
#include "anim_Idle.inc.c"
#include "anim_Slow gait.inc.c"
#include "anim_Look down stop walk.inc.c"
#include "anim_Look up start walk.inc.c"
#include "anim_Flip down.inc.c"
#include "anim_Lay down.inc.c"
#include "anim_Run start.inc.c"
#include "anim_Run.inc.c"
#include "anim_Run stop.inc.c"
#include "anim_Run slip.inc.c"
#include "anim_Fire breath quick.inc.c"
#include "anim_Edge move.inc.c"
#include "anim_Edge stop.inc.c"
#include "anim_Flip.inc.c"
#include "anim_Stand up from flip.inc.c"
