extern const GeoLayout thwompgate_geo[];
extern Lights1 thwompgate_Grill_lights;
extern u8 thwompgate_ChainLink_ia8[];
extern Vtx thwompgate_Gate_mesh_layer_4_vtx_cull[8];
extern Vtx thwompgate_Gate_mesh_layer_4_vtx_0[4];
extern Gfx thwompgate_Gate_mesh_layer_4_tri_0[];
extern Gfx mat_thwompgate_Grill[];
extern Gfx mat_revert_thwompgate_Grill[];
extern Gfx thwompgate_Gate_mesh_layer_4[];
extern Gfx thwompgate_material_revert_render_settings[];
