#include "levels/ccm/area_1/geo.inc.c"
#include "levels/ccm/area_2/geo.inc.c"
#include "levels/ccm/area_3/geo.inc.c"
#include "levels/ccm/area_4/geo.inc.c"
#include "levels/ccm/area_5/geo.inc.c"
#include "levels/ccm/area_6/geo.inc.c"
