#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ccm/header.h"

#include "levels/ccm/ropeway_lift/geo.inc.c"
#include "levels/ccm/snowman_base/geo.inc.c"
#include "levels/ccm/snowman_head/geo.inc.c"
#include "levels/ccm/areas/1/6/geo.inc.c"
#include "levels/ccm/areas/1/7/geo.inc.c"
#include "levels/ccm/areas/1/8/geo.inc.c"
#include "levels/ccm/areas/1/9/geo.inc.c"
#include "levels/ccm/areas/1/10/geo.inc.c"
#include "levels/ccm/areas/1/geo.inc.c"
#include "levels/ccm/areas/2/geo.inc.c"
#include "levels/ccm/geo.inc.c"

#include "levels/ccm/fan/geo.inc.c"
#include "levels/ccm/crab/geo.inc.c"
#include "levels/ccm/bone_plat/geo.inc.c"
#include "levels/ccm/bone_elevator/geo.inc.c"
#include "levels/ccm/bone_train/geo.inc.c"
#include "levels/ccm/bonespin/geo.inc.c"
#include "levels/ccm/bonespin2/geo.inc.c"
#include "levels/ccm/bonegate/geo.inc.c"
#include "levels/ccm/boneswapgate/geo.inc.c"
#include "levels/ccm/corenode/geo.inc.c"
#include "levels/ccm/nullbody/geo.inc.c"
#include "levels/ccm/can/geo.inc.c"
#include "levels/ccm/trashbag/geo.inc.c"
#include "levels/ccm/puddlepoop/geo.inc.c"
#include "levels/ccm/pipe1_ccm/geo.inc.c"
#include "levels/ccm/pipe2_ccm/geo.inc.c"
#include "levels/ccm/conv1_ccm/geo.inc.c"
#include "levels/ccm/conv2_ccm/geo.inc.c"
#include "levels/ccm/executive/geo.inc.c"
#include "levels/ccm/cosmic_missile/geo.inc.c"
#include "levels/ccm/conv1ccm/geo.inc.c"
#include "levels/ccm/conv2ccm/geo.inc.c"