#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/rr/header.h"

#include "levels/rr/areas/1/2/geo.inc.c"
#include "levels/rr/areas/1/3/geo.inc.c"
#include "levels/rr/areas/1/4/geo.inc.c"
#include "levels/rr/areas/1/5/geo.inc.c"
#include "levels/rr/areas/1/6/geo.inc.c"
#include "levels/rr/areas/1/7/geo.inc.c"
#include "levels/rr/areas/1/8/geo.inc.c"
#include "levels/rr/areas/1/9/geo.inc.c"
#include "levels/rr/areas/1/10/geo.inc.c"
#include "levels/rr/areas/1/11/geo.inc.c"
#include "levels/rr/areas/1/12/geo.inc.c"
#include "levels/rr/areas/1/13/geo.inc.c"
#include "levels/rr/areas/1/14/geo.inc.c"
#include "levels/rr/areas/1/15/geo.inc.c"
#include "levels/rr/areas/1/16/geo.inc.c"
#include "levels/rr/areas/1/17/geo.inc.c"
#include "levels/rr/areas/1/18/geo.inc.c"
#include "levels/rr/areas/1/19/geo.inc.c"
#include "levels/rr/areas/1/20/geo.inc.c"
#include "levels/rr/areas/1/21/geo.inc.c"
#include "levels/rr/flying_carpet/geo.inc.c"
#include "levels/rr/swinging_platform/geo.inc.c"
#include "levels/rr/rotating_bridge_platform/geo.inc.c"
#include "levels/rr/cruiser_wing/geo.inc.c"
#include "levels/rr/octagonal_platform/geo.inc.c"
#include "levels/rr/sliding_platform/geo.inc.c"
#include "levels/rr/pyramid_platform/geo.inc.c" // unused
#include "levels/rr/elevator_platform/geo.inc.c"
#include "levels/rr/seesaw_platform/geo.inc.c"
#include "levels/rr/donut_block/geo.inc.c"
#include "levels/rr/l_platform/geo.inc.c" // also unused
#include "levels/rr/tricky_triangles_1/geo.inc.c"
#include "levels/rr/tricky_triangles_2/geo.inc.c"
#include "levels/rr/tricky_triangles_3/geo.inc.c"
#include "levels/rr/tricky_triangles_4/geo.inc.c"
#include "levels/rr/tricky_triangles_5/geo.inc.c"
#include "levels/rr/areas/1/geo.inc.c"

#include "levels/rr/fountain2/geo.inc.c"
#include "levels/rr/geo.inc.c"

#include "levels/rr/blocker/geo.inc.c"
#include "levels/rr/rr_door/geo.inc.c"
#include "levels/rr/rr_tube/geo.inc.c"
#include "levels/rr/rr_eye/geo.inc.c"
#include "levels/rr/rr_pyramid/geo.inc.c"
#include "levels/rr/spinseed/geo.inc.c"
#include "levels/rr/staticflood/geo.inc.c"
#include "levels/rr/blood/geo.inc.c"
#include "levels/rr/palamedes/geo.inc.c"
#include "levels/rr/agheart/geo.inc.c"
#include "levels/rr/agportal/geo.inc.c"
#include "levels/rr/blood_particle/geo.inc.c"
#include "levels/rr/agcrack/geo.inc.c"
#include "levels/rr/agpillar1/geo.inc.c"
#include "levels/rr/agwall/geo.inc.c"
#include "levels/rr/agcrumble/geo.inc.c"
#include "levels/rr/agring/geo.inc.c"
#include "levels/rr/ag_killer_laser/geo.inc.c"
#include "levels/rr/agboom/geo.inc.c"
#include "levels/rr/agmoon/geo.inc.c"
#include "levels/rr/agpillar2/geo.inc.c"
#include "levels/rr/agpillar3/geo.inc.c"
#include "levels/rr/endflames/geo.inc.c"
#include "levels/rr/agtri/geo.inc.c"
#include "levels/rr/form1/geo.inc.c"
#include "levels/rr/form2a/geo.inc.c"
#include "levels/rr/form2/geo.inc.c"
#include "levels/rr/form3/geo.inc.c"
#include "levels/rr/lopalam/geo.inc.c"