extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const MacroObject rr_area_1_macro_objs[];
extern const GeoLayout rr_area_2_geo[];
extern const GeoLayout rr_area_2[];
extern const Collision rr_area_2_collision[];
extern const MacroObject rr_area_2_macro_objs[];
extern const GeoLayout rr_area_3_geo[];
extern const GeoLayout rr_area_3[];
extern const Collision rr_area_3_collision[];
extern const MacroObject rr_area_3_macro_objs[];
extern const GeoLayout rr_area_4_geo[];
extern const GeoLayout rr_area_4[];
extern const Collision rr_area_4_collision[];
extern const MacroObject rr_area_4_macro_objs[];
extern const GeoLayout rr_area_5_geo[];
extern const GeoLayout rr_area_5[];
extern const Collision rr_area_5_collision[];
extern const MacroObject rr_area_5_macro_objs[];
extern const GeoLayout rr_area_6_geo[];
extern const GeoLayout rr_area_6[];
extern const Collision rr_area_6_collision[];
extern const MacroObject rr_area_6_macro_objs[];
extern const GeoLayout rr_area_7_geo[];
extern const GeoLayout rr_area_7[];
extern const Collision rr_area_7_collision[];
extern const MacroObject rr_area_7_macro_objs[];
extern const GeoLayout rr_area_0_geo[];
extern const GeoLayout rr_dl_1room1_geo[];
extern const GeoLayout rr_dl_1room2_geo[];
extern const GeoLayout rr_dl_1room3_geo[];
extern const GeoLayout rr_area_0[];
extern const Collision rr_area_0_collision[];
extern const u8 rr_area_0_collision_rooms[];
extern const MacroObject rr_area_0_macro_objs[];
extern const Trajectory rr_area_0_spline_NurbsCurve[];
extern const Trajectory rr_area_0_spline_NurbsCurve_001[];
extern Lights1 rr_dl_Wall_lights;
extern Lights1 rr_dl_Moon_lights;
extern Lights1 rr_dl_Warning_lights;
extern Lights1 rr_dl_DiamondPlate_lights;
extern Lights1 rr_dl_Grate_lights;
extern Lights1 rr_dl_Warning2_lights;
extern Lights1 rr_dl_Warp_lights;
extern Lights1 rr_dl_Color_lights;
extern Lights1 rr_dl_ElevatorWall_lights;
extern Lights1 rr_dl_ElevatorFloor_lights;
extern Lights1 rr_dl_ElevatorRoof_lights;
extern Lights1 rr_dl_R_Brick_lights;
extern Lights1 rr_dl_Pyramid_Brick_lights;
extern Lights1 rr_dl_Pyramid_Floor_lights;
extern Lights1 rr_dl_Pyramid_Sand_lights;
extern Lights1 rr_dl_Pyramid_Pillar_lights;
extern Lights1 rr_dl_Pyramid_Quicksand_lights;
extern Lights1 rr_dl_grate_lights;
extern Lights1 rr_dl_pool_lights;
extern Lights1 rr_dl_sky_layer0_lights;
extern Lights1 rr_dl_GreyGrass_lights;
extern Lights1 rr_dl_GreyDirt_lights;
extern Lights1 rr_dl_GreyWood_lights;
extern Lights1 rr_dl_Stoner_lights;
extern Lights1 rr_dl_ShinyRock_lights;
extern Lights1 rr_dl_Sign_lights;
extern Lights1 rr_dl_fence_lights;
extern Lights1 rr_dl_flowergrass_lights;
extern Lights1 rr_dl_road_lights;
extern Lights1 rr_dl_gake_wall_lights;
extern Lights1 rr_dl_holey_spike_lights;
extern Lights1 rr_dl_fanmetal_lights;
extern u8 rr_dl_Lights_ci8[];
extern u8 rr_dl_Lights_ci8_pal_rgba16[];
extern u8 rr_dl_Walls_ci8[];
extern u8 rr_dl_Walls_ci8_pal_rgba16[];
extern u8 rr_dl_Rock_ci4_ci4[];
extern u8 rr_dl_Rock_ci4_ci4_pal_rgba16[];
extern u8 rr_dl_Warning_rgba16[];
extern u8 rr_dl_DiamondPlate_rgba16[];
extern u8 rr_dl_ChainLinkFloor_ia8[];
extern u8 rr_dl_Warning2_ci8[];
extern u8 rr_dl_Warning2_ci8_pal_rgba16[];
extern u8 rr_dl_Warp_i8[];
extern u8 rr_dl_rgba16_anonmoose_envmap_silver1_i8[];
extern u8 rr_dl_ElevatorWall_ci8[];
extern u8 rr_dl_ElevatorWall_ci8_pal_rgba16[];
extern u8 rr_dl_TiledMarble_ci8[];
extern u8 rr_dl_TiledMarble_ci8_pal_rgba16[];
extern u8 rr_dl_ElevatorCeiling_ci8[];
extern u8 rr_dl_ElevatorCeiling_ci8_pal_rgba16[];
extern u8 rr_dl_three_ia8[];
extern u8 rr_dl_Monitor_ci8[];
extern u8 rr_dl_Monitor_ci8_pal_rgba16[];
extern u8 rr_dl_Static2_i8[];
extern u8 rr_dl_Metal_rgba16[];
extern u8 rr_dl_Super_Bright_brick_i8[];
extern u8 rr_dl_Desert_Pyramid_ci8[];
extern u8 rr_dl_Desert_Pyramid_ci8_pal_rgba16[];
extern u8 rr_dl_Desert_Pyramid_Floor_ci8[];
extern u8 rr_dl_Desert_Pyramid_Floor_ci8_pal_rgba16[];
extern u8 rr_dl_Desert_Sand_ci8[];
extern u8 rr_dl_Desert_Sand_ci8_pal_rgba16[];
extern u8 rr_dl_Desert_Pillar_ci8[];
extern u8 rr_dl_Desert_Pillar_ci8_pal_rgba16[];
extern u8 rr_dl_Desert_Quicksand_ci8[];
extern u8 rr_dl_Desert_Quicksand_ci8_pal_rgba16[];
extern u8 rr_dl_Desert_Cactus_ci8[];
extern u8 rr_dl_Desert_Cactus_ci8_pal_rgba16[];
extern u8 rr_dl_Tileset_ci4[];
extern u8 rr_dl_Tileset_ci4_pal_rgba16[];
extern u8 rr_dl_Tileset2_ci4[];
extern u8 rr_dl_Tileset2_ci4_pal_rgba16[];
extern u8 rr_dl_cosmicCum_rgba16[];
extern u8 rr_dl_pool_grate_rgba16[];
extern u8 rr_dl_PoolTile_i8[];
extern u8 rr_dl_Water__ci4[];
extern u8 rr_dl_Water__ci4_pal_rgba16[];
extern u8 rr_dl_GreyGrass_i8[];
extern u8 rr_dl_GreyDirt_i8[];
extern u8 rr_dl_GreyWood_i8[];
extern u8 rr_dl_Stoner_i8[];
extern u8 rr_dl_ShinyRock_i8[];
extern u8 rr_dl_ArrowSign_rgba16[];
extern u8 rr_dl_Fence_ia8[];
extern u8 rr_dl_flowers_ci8[];
extern u8 rr_dl_flowers_ci8_pal_rgba16[];
extern u8 rr_dl_flowergrass_ia8[];
extern u8 rr_dl_Path_ia8[];
extern u8 rr_dl_Honey_ci4[];
extern u8 rr_dl_Honey_ci4_pal_rgba16[];
extern u8 rr_dl_gakeside_i8[];
extern u8 rr_dl_HoleySpike_i8[];
extern u8 rr_dl_Earth_rgba16[];
extern u8 rr_dl_Fan1_ci8[];
extern u8 rr_dl_Fan1_ci8_pal_rgba16[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_0[122];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_1[133];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_2[134];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_2[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_3[428];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_3[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_4[185];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_4[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_5[192];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_5[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_6[55];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_6[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_7[24];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_7[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_8[428];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_8[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_9[39];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_9[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_10[8];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_10[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_11[8];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_11[];
extern Vtx rr_dl_Cylinder_mesh_layer_4_vtx_0[22];
extern Gfx rr_dl_Cylinder_mesh_layer_4_tri_0[];
extern Vtx rr_dl_Cylinder_mesh_layer_5_vtx_0[119];
extern Gfx rr_dl_Cylinder_mesh_layer_5_tri_0[];
extern Vtx rr_dl_visual_mesh_layer_6_vtx_0[4];
extern Gfx rr_dl_visual_mesh_layer_6_tri_0[];
extern Vtx rr_dl_visual_mesh_layer_1_vtx_0[12];
extern Gfx rr_dl_visual_mesh_layer_1_tri_0[];
extern Vtx rr_dl_visual_mesh_layer_1_vtx_1[520];
extern Gfx rr_dl_visual_mesh_layer_1_tri_1[];
extern Vtx rr_dl_visual_mesh_layer_1_vtx_2[309];
extern Gfx rr_dl_visual_mesh_layer_1_tri_2[];
extern Vtx rr_dl_visual_mesh_layer_2_vtx_0[125];
extern Gfx rr_dl_visual_mesh_layer_2_tri_0[];
extern Vtx rr_dl_visual_001_mesh_layer_1_vtx_0[35];
extern Gfx rr_dl_visual_001_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx rr_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx rr_dl_solid_mesh_layer_1_vtx_0[576];
extern Gfx rr_dl_solid_mesh_layer_1_tri_0[];
extern Vtx rr_dl_solid_mesh_layer_1_vtx_1[72];
extern Gfx rr_dl_solid_mesh_layer_1_tri_1[];
extern Vtx rr_dl_solid_mesh_layer_1_vtx_2[358];
extern Gfx rr_dl_solid_mesh_layer_1_tri_2[];
extern Vtx rr_dl_solid_mesh_layer_1_vtx_3[252];
extern Gfx rr_dl_solid_mesh_layer_1_tri_3[];
extern Vtx rr_dl_solid_mesh_layer_1_vtx_4[24];
extern Gfx rr_dl_solid_mesh_layer_1_tri_4[];
extern Vtx rr_dl_vis_002_mesh_layer_4_vtx_0[104];
extern Gfx rr_dl_vis_002_mesh_layer_4_tri_0[];
extern Vtx rr_dl_vis_001_mesh_layer_4_vtx_0[2892];
extern Gfx rr_dl_vis_001_mesh_layer_4_tri_0[];
extern Vtx rr_dl_vis_001_mesh_layer_4_vtx_1[212];
extern Gfx rr_dl_vis_001_mesh_layer_4_tri_1[];
extern Vtx rr_dl_vis_001_mesh_layer_1_vtx_0[4];
extern Gfx rr_dl_vis_001_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Cube_005_mesh_layer_1_vtx_0[737];
extern Gfx rr_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Cube_007_mesh_layer_1_vtx_0[64];
extern Gfx rr_dl_Cube_007_mesh_layer_1_tri_0[];
extern Vtx rr_dl_maze_mesh_layer_1_vtx_0[50];
extern Gfx rr_dl_maze_mesh_layer_1_tri_0[];
extern Vtx rr_dl_maze_mesh_layer_1_vtx_1[1540];
extern Gfx rr_dl_maze_mesh_layer_1_tri_1[];
extern Vtx rr_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx rr_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx rr_dl_aaaa_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_aaaa_mesh_layer_0_vtx_0[26];
extern Gfx rr_dl_aaaa_mesh_layer_0_tri_0[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_0[447];
extern Gfx rr_dl_node_mesh_layer_1_tri_0[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_1[614];
extern Gfx rr_dl_node_mesh_layer_1_tri_1[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_2[218];
extern Gfx rr_dl_node_mesh_layer_1_tri_2[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_3[263];
extern Gfx rr_dl_node_mesh_layer_1_tri_3[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_4[137];
extern Gfx rr_dl_node_mesh_layer_1_tri_4[];
extern Vtx rr_dl_node_mesh_layer_1_vtx_5[20];
extern Gfx rr_dl_node_mesh_layer_1_tri_5[];
extern Vtx rr_dl_node_001_mesh_layer_4_vtx_0[40];
extern Gfx rr_dl_node_001_mesh_layer_4_tri_0[];
extern Vtx rr_dl_node_001_mesh_layer_4_vtx_1[120];
extern Gfx rr_dl_node_001_mesh_layer_4_tri_1[];
extern Vtx rr_dl_node_001_mesh_layer_4_vtx_2[96];
extern Gfx rr_dl_node_001_mesh_layer_4_tri_2[];
extern Vtx rr_dl_node_002_mesh_layer_4_vtx_0[177];
extern Gfx rr_dl_node_002_mesh_layer_4_tri_0[];
extern Vtx rr_dl_Water_Box_Mesh_001_mesh_layer_5_vtx_cull[8];
extern Vtx rr_dl_Water_Box_Mesh_001_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_Water_Box_Mesh_001_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vis_mesh_layer_1_vtx_0[12];
extern Gfx rr_dl_vis_mesh_layer_1_tri_0[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_0[39];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_0[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_1[8];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_1[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_2[8];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_2[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_3[28];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_3[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_4[100];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_4[];
extern Vtx rr_dl_vis_col_mesh_layer_1_vtx_5[84];
extern Gfx rr_dl_vis_col_mesh_layer_1_tri_5[];
extern Vtx rr_dl_earth_mesh_layer_1_vtx_0[172];
extern Gfx rr_dl_earth_mesh_layer_1_tri_0[];
extern Vtx rr_dl_staticroom_mesh_layer_1_vtx_0[20];
extern Gfx rr_dl_staticroom_mesh_layer_1_tri_0[];
extern Vtx rr_dl_staticroom_mesh_layer_1_vtx_1[72];
extern Gfx rr_dl_staticroom_mesh_layer_1_tri_1[];
extern Vtx rr_dl_staticroom_mesh_layer_4_vtx_0[6];
extern Gfx rr_dl_staticroom_mesh_layer_4_tri_0[];
extern Vtx rr_dl_final_cutscene_mesh_layer_1_vtx_0[74];
extern Gfx rr_dl_final_cutscene_mesh_layer_1_tri_0[];
extern Gfx mat_rr_dl_Light[];
extern Gfx mat_revert_rr_dl_Light[];
extern Gfx mat_rr_dl_Wall[];
extern Gfx mat_revert_rr_dl_Wall[];
extern Gfx mat_rr_dl_Moon[];
extern Gfx mat_revert_rr_dl_Moon[];
extern Gfx mat_rr_dl_Warning[];
extern Gfx mat_revert_rr_dl_Warning[];
extern Gfx mat_rr_dl_DiamondPlate[];
extern Gfx mat_revert_rr_dl_DiamondPlate[];
extern Gfx mat_rr_dl_Grate[];
extern Gfx mat_revert_rr_dl_Grate[];
extern Gfx mat_rr_dl_Warning2[];
extern Gfx mat_revert_rr_dl_Warning2[];
extern Gfx mat_rr_dl_Warp[];
extern Gfx mat_revert_rr_dl_Warp[];
extern Gfx mat_rr_dl_Color[];
extern Gfx mat_revert_rr_dl_Color[];
extern Gfx mat_rr_dl_glass[];
extern Gfx mat_rr_dl_metal[];
extern Gfx mat_revert_rr_dl_metal[];
extern Gfx mat_rr_dl_ElevatorWall[];
extern Gfx mat_revert_rr_dl_ElevatorWall[];
extern Gfx mat_rr_dl_ElevatorFloor[];
extern Gfx mat_revert_rr_dl_ElevatorFloor[];
extern Gfx mat_rr_dl_ElevatorRoof[];
extern Gfx mat_revert_rr_dl_ElevatorRoof[];
extern Gfx mat_rr_dl_three[];
extern Gfx mat_rr_dl_monitor[];
extern Gfx mat_revert_rr_dl_monitor[];
extern Gfx mat_rr_dl_static_quicksand[];
extern Gfx mat_revert_rr_dl_static_quicksand[];
extern Gfx mat_rr_dl_cosmic_seed[];
extern Gfx mat_revert_rr_dl_cosmic_seed[];
extern Gfx mat_rr_dl_R_Brick[];
extern Gfx mat_revert_rr_dl_R_Brick[];
extern Gfx mat_rr_dl_Pyramid_Brick[];
extern Gfx mat_revert_rr_dl_Pyramid_Brick[];
extern Gfx mat_rr_dl_Pyramid_Floor[];
extern Gfx mat_revert_rr_dl_Pyramid_Floor[];
extern Gfx mat_rr_dl_Pyramid_Sand[];
extern Gfx mat_revert_rr_dl_Pyramid_Sand[];
extern Gfx mat_rr_dl_Pyramid_Pillar[];
extern Gfx mat_revert_rr_dl_Pyramid_Pillar[];
extern Gfx mat_rr_dl_Pyramid_Quicksand[];
extern Gfx mat_revert_rr_dl_Pyramid_Quicksand[];
extern Gfx mat_rr_dl_Cactus[];
extern Gfx mat_revert_rr_dl_Cactus[];
extern Gfx mat_rr_dl_Tileset[];
extern Gfx mat_revert_rr_dl_Tileset[];
extern Gfx mat_rr_dl_Tileset_Grate[];
extern Gfx mat_revert_rr_dl_Tileset_Grate[];
extern Gfx mat_rr_dl_f3d_material_layer1[];
extern Gfx mat_revert_rr_dl_f3d_material_layer1[];
extern Gfx mat_rr_dl_grate[];
extern Gfx mat_revert_rr_dl_grate[];
extern Gfx mat_rr_dl_pool[];
extern Gfx mat_revert_rr_dl_pool[];
extern Gfx mat_rr_dl_sm64_water_mat[];
extern Gfx mat_revert_rr_dl_sm64_water_mat[];
extern Gfx mat_rr_dl_sky_layer0[];
extern Gfx mat_revert_rr_dl_sky_layer0[];
extern Gfx mat_rr_dl_GreyGrass[];
extern Gfx mat_revert_rr_dl_GreyGrass[];
extern Gfx mat_rr_dl_GreyDirt[];
extern Gfx mat_revert_rr_dl_GreyDirt[];
extern Gfx mat_rr_dl_GreyWood[];
extern Gfx mat_revert_rr_dl_GreyWood[];
extern Gfx mat_rr_dl_Stoner[];
extern Gfx mat_revert_rr_dl_Stoner[];
extern Gfx mat_rr_dl_ShinyRock[];
extern Gfx mat_revert_rr_dl_ShinyRock[];
extern Gfx mat_rr_dl_Sign[];
extern Gfx mat_revert_rr_dl_Sign[];
extern Gfx mat_rr_dl_fence[];
extern Gfx mat_revert_rr_dl_fence[];
extern Gfx mat_rr_dl_flowers[];
extern Gfx mat_revert_rr_dl_flowers[];
extern Gfx mat_rr_dl_flowergrass[];
extern Gfx mat_revert_rr_dl_flowergrass[];
extern Gfx mat_rr_dl_road[];
extern Gfx mat_revert_rr_dl_road[];
extern Gfx mat_rr_dl_sm64_water_mat_2[];
extern Gfx mat_revert_rr_dl_sm64_water_mat_2[];
extern Gfx mat_rr_dl_gake_wall[];
extern Gfx mat_revert_rr_dl_gake_wall[];
extern Gfx mat_rr_dl_holey_spike[];
extern Gfx mat_rr_dl_earth_decor[];
extern Gfx mat_rr_dl_static_quicksand_darker[];
extern Gfx mat_revert_rr_dl_static_quicksand_darker[];
extern Gfx mat_rr_dl_fanmetal[];
extern Gfx mat_revert_rr_dl_fanmetal[];
extern Gfx rr_dl_Cylinder_mesh_layer_1[];
extern Gfx rr_dl_Cylinder_mesh_layer_4[];
extern Gfx rr_dl_Cylinder_mesh_layer_5[];
extern Gfx rr_dl_visual_mesh_layer_6[];
extern Gfx rr_dl_visual_mesh_layer_1[];
extern Gfx rr_dl_visual_mesh_layer_2[];
extern Gfx rr_dl_visual_001_mesh_layer_1[];
extern Gfx rr_dl_Plane_mesh_layer_1[];
extern Gfx rr_dl_solid_mesh_layer_1[];
extern Gfx rr_dl_vis_002_mesh_layer_4[];
extern Gfx rr_dl_vis_001_mesh_layer_4[];
extern Gfx rr_dl_vis_001_mesh_layer_1[];
extern Gfx rr_dl_Cube_005_mesh_layer_1[];
extern Gfx rr_dl_Cube_007_mesh_layer_1[];
extern Gfx rr_dl_maze_mesh_layer_1[];
extern Gfx rr_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx rr_dl_aaaa_mesh_layer_0[];
extern Gfx rr_dl_node_mesh_layer_1[];
extern Gfx rr_dl_node_001_mesh_layer_4[];
extern Gfx rr_dl_node_002_mesh_layer_4[];
extern Gfx rr_dl_Water_Box_Mesh_001_mesh_layer_5[];
extern Gfx rr_dl_vis_mesh_layer_1[];
extern Gfx rr_dl_vis_col_mesh_layer_1[];
extern Gfx rr_dl_earth_mesh_layer_1[];
extern Gfx rr_dl_staticroom_mesh_layer_1[];
extern Gfx rr_dl_staticroom_mesh_layer_4[];
extern Gfx rr_dl_final_cutscene_mesh_layer_1[];
extern Gfx rr_dl_material_revert_render_settings[];
