extern const GeoLayout ferriscart_geo[];
extern Lights1 ferriscart_f3d_material_002_lights;
extern u8 ferriscart_feriswheelcart_ci8[];
extern u8 ferriscart_feriswheelcart_ci8_pal_rgba16[];
extern Vtx ferriscart_Cube_011_mesh_layer_1_vtx_0[108];
extern Gfx ferriscart_Cube_011_mesh_layer_1_tri_0[];
extern Gfx mat_ferriscart_f3d_material_002[];
extern Gfx mat_revert_ferriscart_f3d_material_002[];
extern Gfx ferriscart_Cube_011_mesh_layer_1[];
extern Gfx ferriscart_material_revert_render_settings[];
