extern const GeoLayout badsign_geo[];
extern Lights1 badsign_mile_sign_lights;
extern u8 badsign_silver_truck_i8[];
extern u8 badsign_MileSign_ci4[];
extern u8 badsign_MileSign_ci4_pal_rgba16[];
extern Vtx badsign_sign_mesh_layer_1_vtx_cull[8];
extern Vtx badsign_sign_mesh_layer_1_vtx_0[27];
extern Gfx badsign_sign_mesh_layer_1_tri_0[];
extern Vtx badsign_sign_mesh_layer_4_vtx_cull[8];
extern Vtx badsign_sign_mesh_layer_4_vtx_0[4];
extern Gfx badsign_sign_mesh_layer_4_tri_0[];
extern Gfx mat_badsign_Metal[];
extern Gfx mat_revert_badsign_Metal[];
extern Gfx mat_badsign_mile_sign[];
extern Gfx mat_revert_badsign_mile_sign[];
extern Gfx badsign_sign_mesh_layer_1[];
extern Gfx badsign_sign_mesh_layer_4[];
extern Gfx badsign_material_revert_render_settings[];
