extern const GeoLayout fountain2_geo[];
extern Vtx fountain2_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx fountain2_Cylinder_mesh_layer_1_vtx_0[350];
extern Gfx fountain2_Cylinder_mesh_layer_1_tri_0[];
extern Vtx fountain2_Cylinder_mesh_layer_5_vtx_cull[8];
extern Vtx fountain2_Cylinder_mesh_layer_5_vtx_0[86];
extern Gfx fountain2_Cylinder_mesh_layer_5_tri_0[];
extern Gfx mat_fountain2_Fountain[];
extern Gfx mat_fountain2_FountainGlow[];
extern Gfx fountain2_Cylinder_mesh_layer_1[];
extern Gfx fountain2_Cylinder_mesh_layer_5[];
extern Gfx fountain2_material_revert_render_settings[];
