#include "src/game/envfx_snow.h"

const GeoLayout lll_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, lll_dl_1room_geo),
			GEO_BRANCH(1, lll_dl_2room_geo),
			GEO_BRANCH(1, lll_dl_3room_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -290, 0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout lll_dl_1room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -290, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 9916, 1739, -5066, lll_dl_barrier_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 7367, 1721, 240, lll_dl_barrier_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 4580, 334, -3160, lll_dl_CoffeeTable_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_CoffeeTable_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 2778, 607, -3160, lll_dl_couch_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 4580, 607, -5374, 0, -90, 0, lll_dl_couch_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8593, 1849, 1202, lll_dl_Cube_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 10154, 4850, 1201, lll_dl_Cylinder_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 10385, 1829, 1201, lll_dl_DiningTable_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 4581, 897, -3172, 0, 90, 0, lll_dl_Flower_001_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 10385, 2553, 1201, lll_dl_Pot_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 4580, 721, -3148, 0, 90, 0, lll_dl_Pot_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 7977, 1798, -1328, lll_dl_rays_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_rays_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_rays_mesh_layer_0),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 13253, 2629, -884, lll_dl_Shelf_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_structure_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_structure_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, -1208, 16, 0, lll_dl_structure_001_mesh_layer_6),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 4715, 191, 755, lll_dl_y_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout lll_dl_2room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -290, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 10260, 4138, 7070, lll_dl_Cylinder_002_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_z0_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_z0_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, -1217, lll_dl_z1_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_z1_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_z1_mesh_layer_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout lll_dl_3room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -290, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8651, 2182, -9998, lll_dl_z3_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_z3_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_z3_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8310, 4138, -13020, lll_dl_z4_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 8769, 2343, -8195, 0, -63, 0, lll_dl_Pot_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 8779, 2519, -8173, 0, -63, 0, lll_dl_Flower_001_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 9002, 2494, -12331, lll_dl_z7_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_z7_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_z7_mesh_layer_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout lll_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 290, 0, 0, 190, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, lll_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_NORMAL, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, lll_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
