#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "macros.h"
#include "surface_terrains.h"
#include "types.h"
#include "make_const_nonconst.h"

#include "mario/model.inc.c"

#include "Hammerbro/model.inc.c"
#include "Hammerbro/anims/data.inc.c"
#include "Hammerbro/anims/table.inc.c"
#include "hammer/model.inc.c"

#include "actors/crab/model.inc.c"
#include "crab_anims/anims/data.inc.c"
#include "crab_anims/anims/table.inc.c"

#include "Rex/model.inc.c"
#include "Rex/anims/data.inc.c"
#include "Rex/anims/table.inc.c"

#include "rocket_boot/model.inc.c"
#include "vanetalc/model.inc.c"
#include "rb_hud/model.inc.c"
#include "rb_bar/model.inc.c"
#include "ico_mana/model.inc.c"
#include "ico_badge/model.inc.c"
// #include "bs_hud/model.inc.c"
// #include "bs_bar/model.inc.c"

#include "exclamation_box/model.inc.c"
#include "podoboo/model.inc.c"

#include "b0/model.inc.c"
#include "b1/model.inc.c"
#include "b2/model.inc.c"
#include "b3/model.inc.c"
#include "b4/model.inc.c"
#include "b5/model.inc.c"
#include "b6/model.inc.c"
#include "b7/model.inc.c"
#include "b8/model.inc.c"
#include "b9/model.inc.c"
#include "b10/model.inc.c"
#include "b11/model.inc.c"
// #include "bE/model.inc.c"
#include "b12/model.inc.c"
#include "b13/model.inc.c"
#include "b14/model.inc.c"
#include "b15/model.inc.c"
#include "b16/model.inc.c"
#include "b21/model.inc.c"
#include "b22/model.inc.c"
#include "b17/model.inc.c"
#include "b23/model.inc.c"
#include "b20/model.inc.c"
#include "b18/model.inc.c"
#include "b19/model.inc.c"

#include "chicken/model.inc.c"
#include "chicken/anims/data.inc.c"
#include "chicken/anims/table.inc.c"

#include "egg/model.inc.c"