#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/wdw/header.h"

#include "levels/wdw/square_floating_platform/geo.inc.c"
#include "levels/wdw/arrow_lift/geo.inc.c"
#include "levels/wdw/water_level_diamond/geo.inc.c"
#include "levels/wdw/hidden_platform/geo.inc.c"
#include "levels/wdw/express_elevator/geo.inc.c"
#include "levels/wdw/rectangular_floating_platform/geo.inc.c"
#include "levels/wdw/rotating_platform/geo.inc.c"
#include "levels/wdw/areas/1/geo.inc.c"
#include "levels/wdw/areas/2/geo.inc.c"

#include "levels/wdw/geo.inc.c"

#include "levels/wdw/projector/geo.inc.c"
#include "levels/wdw/movie_1/geo.inc.c"
#include "levels/wdw/projector_handle/geo.inc.c"
#include "levels/wdw/movie_2/geo.inc.c"
#include "levels/wdw/cone/geo.inc.c"
#include "levels/wdw/balloon/geo.inc.c"
#include "levels/wdw/stopsign/geo.inc.c"
#include "levels/wdw/streetlight/geo.inc.c"
#include "levels/wdw/ferris/geo.inc.c"
#include "levels/wdw/ferriscart/geo.inc.c"
#include "levels/wdw/press/geo.inc.c"
#include "levels/wdw/girl/geo.inc.c"
#include "levels/wdw/movie8/geo.inc.c"
#include "levels/wdw/movie_9/geo.inc.c"
#include "levels/wdw/star_sign/geo.inc.c"
#include "levels/wdw/cobie2/geo.inc.c"
#include "levels/wdw/moleman2/geo.inc.c"
#include "levels/wdw/edward2/geo.inc.c"
#include "levels/wdw/robozo2/geo.inc.c"