extern const GeoLayout dcoin_Bone_opt1[];
extern const GeoLayout dcoin_Bone_opt2[];
extern const GeoLayout dcoin_Bone_opt3[];
extern const GeoLayout dcoin_Bone_opt4[];
extern const GeoLayout dcoin_geo[];
extern Lights1 dcoin_coin1_lights;
extern Lights1 dcoin_coin2_lights;
extern Lights1 dcoin_coin3_lights;
extern Lights1 dcoin_coin4_lights;
extern Lights1 dcoin_coin5_lights;
extern u8 dcoin_DC_1_ci4[];
extern u8 dcoin_DC_1_ci4_pal_rgba16[];
extern u8 dcoin_DC_2_ci4[];
extern u8 dcoin_DC_2_ci4_pal_rgba16[];
extern u8 dcoin_DC_3_ci4[];
extern u8 dcoin_DC_3_ci4_pal_rgba16[];
extern u8 dcoin_DC_4_ci4[];
extern u8 dcoin_DC_4_ci4_pal_rgba16[];
extern u8 dcoin_DC_5_ia8[];
extern Vtx dcoin_Coin_mesh_layer_4_vtx_0[4];
extern Gfx dcoin_Coin_mesh_layer_4_tri_0[];
extern Gfx mat_dcoin_coin1[];
extern Gfx mat_revert_dcoin_coin1[];
extern Gfx mat_dcoin_coin2[];
extern Gfx mat_revert_dcoin_coin2[];
extern Gfx mat_dcoin_coin3[];
extern Gfx mat_revert_dcoin_coin3[];
extern Gfx mat_dcoin_coin4[];
extern Gfx mat_revert_dcoin_coin4[];
extern Gfx mat_dcoin_coin5[];
extern Gfx mat_revert_dcoin_coin5[];
extern Gfx dcoin_Coin_mesh_layer_4[];
extern Gfx dcoin_Coin_mesh_layer_4_mat_override_coin2_0[];
extern Gfx dcoin_Coin_mesh_layer_4_mat_override_coin3_1[];
extern Gfx dcoin_Coin_mesh_layer_4_mat_override_coin4_2[];
extern Gfx dcoin_Coin_mesh_layer_4_mat_override_coin5_3[];
extern Gfx dcoin_material_revert_render_settings[];
