extern const GeoLayout HH_root_opt1[];
extern const GeoLayout HH_root_opt2[];
extern const GeoLayout HH_root_opt3[];
extern const GeoLayout HH_root_opt4[];
extern const GeoLayout HH_geo[];
extern Lights1 HH_HH_Default_lights;
extern Lights1 HH_HH_Circle_lights;
extern Lights1 HH_HH_Square_lights;
extern Lights1 HH_HH_Triangle_lights;
extern Lights1 HH_HH_Star_lights;
extern u8 HH_HH_default_ci8[];
extern u8 HH_HH_default_ci8_pal_rgba16[];
extern u8 HH_HH_circle_ci8[];
extern u8 HH_HH_circle_ci8_pal_rgba16[];
extern u8 HH_HH_square_ci8[];
extern u8 HH_HH_square_ci8_pal_rgba16[];
extern u8 HH_HH_Triangle_ci8[];
extern u8 HH_HH_Triangle_ci8_pal_rgba16[];
extern u8 HH_HH_Star_ci8[];
extern u8 HH_HH_Star_ci8_pal_rgba16[];
extern Vtx HH_boner_mesh_layer_1_vtx_0[36];
extern Gfx HH_boner_mesh_layer_1_tri_0[];
extern Gfx mat_HH_HH_Default[];
extern Gfx mat_revert_HH_HH_Default[];
extern Gfx mat_HH_HH_Circle[];
extern Gfx mat_revert_HH_HH_Circle[];
extern Gfx mat_HH_HH_Square[];
extern Gfx mat_revert_HH_HH_Square[];
extern Gfx mat_HH_HH_Triangle[];
extern Gfx mat_revert_HH_HH_Triangle[];
extern Gfx mat_HH_HH_Star[];
extern Gfx mat_revert_HH_HH_Star[];
extern Gfx HH_boner_mesh_layer_1[];
extern Gfx HH_boner_mesh_layer_1_mat_override_HH_Circle_0[];
extern Gfx HH_boner_mesh_layer_1_mat_override_HH_Square_1[];
extern Gfx HH_boner_mesh_layer_1_mat_override_HH_Triangle_2[];
extern Gfx HH_boner_mesh_layer_1_mat_override_HH_Star_3[];
extern Gfx HH_material_revert_render_settings[];
