extern const GeoLayout retrothwomp_geo[];
extern u8 retrothwomp_SMB3_Thwomp_ci4[];
extern u8 retrothwomp_SMB3_Thwomp_ci4_pal_rgba16[];
extern Vtx retrothwomp_Cube_004_mesh_layer_4_vtx_cull[8];
extern Vtx retrothwomp_Cube_004_mesh_layer_4_vtx_0[4];
extern Gfx retrothwomp_Cube_004_mesh_layer_4_tri_0[];
extern Gfx mat_retrothwomp_Thwomp[];
extern Gfx mat_revert_retrothwomp_Thwomp[];
extern Gfx retrothwomp_Cube_004_mesh_layer_4[];
extern Gfx retrothwomp_material_revert_render_settings[];
