extern const GeoLayout pode_seg_geo[];
extern Lights1 pode_seg_pode_body_lights;
extern u8 pode_seg_Pode_Body_ci8[];
extern u8 pode_seg_Pode_Body_ci8_pal_rgba16[];
extern Vtx pode_seg_dl_mesh_layer_1_vtx_0[32];
extern Gfx pode_seg_dl_mesh_layer_1_tri_0[];
extern Vtx pode_seg_dl_mesh_layer_1_vtx_1[36];
extern Gfx pode_seg_dl_mesh_layer_1_tri_1[];
extern Gfx mat_pode_seg_pode_body[];
extern Gfx mat_revert_pode_seg_pode_body[];
extern Gfx mat_pode_seg_spike[];
extern Gfx mat_revert_pode_seg_spike[];
extern Gfx pode_seg_dl_mesh_layer_1[];
extern Gfx pode_seg_material_revert_render_settings[];
