extern const GeoLayout blue_coin_switch_geo[];
extern Lights1 blue_coin_switch_sides_lights;
extern Lights1 blue_coin_switch_top_lights;
extern u8 blue_coin_switch_blue_coin_switch_side_rgba16[];
extern u8 blue_coin_switch_blue_coin_switch_top_rgba16[];
extern Vtx blue_coin_switch_Blue_coin_switch_model_mesh_layer_1_vtx_0[16];
extern Vtx blue_coin_switch_Blue_coin_switch_model_mesh_layer_1_vtx_1[4];
extern Gfx blue_coin_switch_Blue_coin_switch_model_mesh_layer_1[];
extern Gfx blue_coin_switch_material_revert_render_settings[];
