extern const GeoLayout conveyor_half_000_switch_opt1[];
extern const GeoLayout conveyor_half_000_switch_opt2[];
extern const GeoLayout conveyor_half_geo[];
extern Lights1 conveyor_half_conveyor_top_lights;
extern Lights1 conveyor_half_conveyor_side_lights;
extern Lights1 conveyor_half_conveyor_top_red_lights;
extern Lights1 conveyor_half_conveyor_top_blue_lights;
extern u8 conveyor_half_conveyor_top_rgba16[];
extern u8 conveyor_half_conveyor_side_i8[];
extern u8 conveyor_half_conveyor_top_red_ci8[];
extern u8 conveyor_half_conveyor_top_red_ci8_pal_rgba16[];
extern u8 conveyor_half_conveyor_top_blue_ci8[];
extern u8 conveyor_half_conveyor_top_blue_ci8_pal_rgba16[];
extern Vtx conveyor_half_000_displaylist_mesh_layer_1_vtx_0[16];
extern Gfx conveyor_half_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx conveyor_half_000_displaylist_mesh_layer_1_vtx_1[8];
extern Gfx conveyor_half_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_conveyor_half_conveyor_top[];
extern Gfx mat_conveyor_half_conveyor_side[];
extern Gfx mat_conveyor_half_conveyor_top_red[];
extern Gfx mat_revert_conveyor_half_conveyor_top_red[];
extern Gfx mat_conveyor_half_conveyor_top_blue[];
extern Gfx mat_revert_conveyor_half_conveyor_top_blue[];
extern Gfx conveyor_half_000_displaylist_mesh_layer_1[];
extern Gfx conveyor_half_000_displaylist_mesh_layer_1_mat_override_conveyor_top_red_0[];
extern Gfx conveyor_half_000_displaylist_mesh_layer_1_mat_override_conveyor_top_blue_1[];
extern Gfx conveyor_half_material_revert_render_settings[];
