extern const GeoLayout retrodonut_geo[];
extern u8 retrodonut_Donut_ci4[];
extern u8 retrodonut_Donut_ci4_pal_rgba16[];
extern Vtx retrodonut_Plane_004_mesh_layer_4_vtx_cull[8];
extern Vtx retrodonut_Plane_004_mesh_layer_4_vtx_0[4];
extern Gfx retrodonut_Plane_004_mesh_layer_4_tri_0[];
extern Gfx mat_retrodonut_Donut[];
extern Gfx mat_revert_retrodonut_Donut[];
extern Gfx retrodonut_Plane_004_mesh_layer_4[];
extern Gfx retrodonut_material_revert_render_settings[];
