extern const GeoLayout edward2_geo[];
extern u8 edward2_EdwardFace_ia8[];
extern u8 edward2_EdwardBody_ia8[];
extern Vtx edward2_root_mesh_layer_5_vtx_0[16];
extern Gfx edward2_root_mesh_layer_5_tri_0[];
extern Vtx edward2_bill_mesh_layer_4_vtx_0[4];
extern Gfx edward2_bill_mesh_layer_4_tri_0[];
extern Gfx mat_edward2_EdwardFace[];
extern Gfx mat_edward2_EdwardSkin[];
extern Gfx edward2_root_mesh_layer_5[];
extern Gfx edward2_bill_mesh_layer_4[];
extern Gfx edward2_material_revert_render_settings[];
