extern const GeoLayout twisty_geo[];
extern Lights1 twisty_StarSide_lights;
extern Lights1 twisty_TownFloor_lights;
extern u8 twisty_StarSide_ci8[];
extern u8 twisty_StarSide_ci8_pal_rgba16[];
extern u8 twisty_Townfloor_ci8[];
extern u8 twisty_Townfloor_ci8_pal_rgba16[];
extern Vtx twisty_Cube_002_mesh_layer_1_vtx_0[112];
extern Gfx twisty_Cube_002_mesh_layer_1_tri_0[];
extern Vtx twisty_Cube_002_mesh_layer_1_vtx_1[42];
extern Gfx twisty_Cube_002_mesh_layer_1_tri_1[];
extern Gfx mat_twisty_StarSide[];
extern Gfx mat_revert_twisty_StarSide[];
extern Gfx mat_twisty_TownFloor[];
extern Gfx mat_revert_twisty_TownFloor[];
extern Gfx twisty_Cube_002_mesh_layer_1[];
extern Gfx twisty_material_revert_render_settings[];
