#include "levels/bits/texture_include.inc.c"
#include "levels/bits/area_1/collision.inc.c"
#include "levels/bits/area_1/macro.inc.c"
#include "levels/bits/area_1/spline.inc.c"
#include "levels/bits/model.inc.c"
