#include "src/game/envfx_snow.h"

const GeoLayout castle_inside_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1971, 4176, 0, castle_inside_dl_1Transparent_Solid_001_mesh_layer_1),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(0, 1), geo_painting_draw),
		GEO_ASM(PAINTING_ID(1, 1), geo_painting_draw),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_abaDOOR_TRANSITION_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, 13, 0, castle_inside_dl_Carpet_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Cube_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2880, 300, 909, 0, 45, 0, castle_inside_dl_Cube_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Transparent_Solid_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 655, 873, 0, castle_inside_dl_visual_002_mesh_layer_5),
		GEO_TRANSLATE_NODE(LAYER_TRANSPARENT, -3178, 0, 0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3576, -148, -2208, 0, -45, 0, castle_inside_dl_2book_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3441, -155, -2154, 0, -90, 0, castle_inside_dl_2candle_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -3576, -271, -2208, 0, -45, 0, castle_inside_dl_2table_mesh_layer_4),
		GEO_ASM(PAINTING_ID(2, 1), geo_painting_draw),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3664, 301, -1693, 0, 45, 0, castle_inside_dl_Cube2_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -3664, 301, -1693, 0, 45, 0, castle_inside_dl_Fence_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -4114, 183, -1233, 90, 0, -135, castle_inside_dl_Light_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -3223, 155, -2124, -180, -45, 0, castle_inside_dl_Torch_mesh_layer_4),
		GEO_ASM(PAINTING_ID(3, 1), geo_painting_draw),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, 7),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2581, 146, 3426, castle_inside_dl_Cube_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Cube_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2772, 31, 2215, castle_inside_dl_Cube_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2772, 31, 2215, castle_inside_dl_Cube_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -2772, 31, 2215, castle_inside_dl_Cube_004Water_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Cube_004Water_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -2581, 146, 3426, castle_inside_dl_Cube_006_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -1971, 114, 5016, castle_inside_dl_Cube_009_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1971, 276, 7134, castle_inside_dl_Cube_010_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Cube_010_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -1971, 114, 5306, castle_inside_dl_Cube_012_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Cube_017_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -1679, 445, 2812, -180, 90, 0, castle_inside_dl_Torch_001_mesh_layer_4),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4282, 475, 645),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 4282, -475, -645, castle_inside_dl_1drroom_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -246, -22, -248, 0, 22, 0, castle_inside_dl_2droom_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -246, -22, -248, 0, 22, 0, castle_inside_dl_3droom_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -705, 165, 3935),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1147, 149, -5990, castle_inside_dl_Cube_014_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Cube_014_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -764, 96, 1479),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 764, -96, -1479, castle_inside_dl_zzzzzzzzzzzzcube_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_zzzzzzzzzzzzcube_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 764, -96, -1479, castle_inside_dl_zzzzzzzzzzzzupercube_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_inside_dl_zzzzzzzzzzzzupercube_mesh_layer_2),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_zzzzzzzzzzzzupercube_mesh_layer_6),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_zzzzzzzzzzzzupercube_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1287, 1523, 2752, castle_inside_dl_dingus_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_inside_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
