#pragma once

#include "engine.h"

enum {
    MB64_BUTTON_SETTINGS,
    MB64_BUTTON_TEST,

    // terrain
    MB64_BUTTON_TERRAIN,
    MB64_BUTTON_SLAB,
    MB64_BUTTON_VSLAB,
    MB64_BUTTON_SLOPE,
    MB64_BUTTON_CORNER,
    MB64_BUTTON_ICORNER,
    MB64_BUTTON_SSLOPE,
    MB64_BUTTON_LGENTLE,
    MB64_BUTTON_UGENTLE,
    MB64_BUTTON_SCORNER,
    MB64_BUTTON_ISCORNER,
    MB64_BUTTON_WATER,
    MB64_BUTTON_FENCE,
    MB64_BUTTON_BARS,
    MB64_BUTTON_POLE,
    MB64_BUTTON_CULL,
    MB64_BUTTON_TROLL,
    MB64_BUTTON_TREE,

    // scenery and collectibles
    MB64_BUTTON_STAR,
    MB64_BUTTON_RED_COIN_STAR,
    MB64_BUTTON_TRIGGER_STAR,
    MB64_BUTTON_TRIGGER,
    MB64_BUTTON_COIN,
    MB64_BUTTON_GCOIN,
    MB64_BUTTON_RCOIN,
    MB64_BUTTON_BCOIN,
    MB64_BUTTON_BLUE_COIN_SWITCH,
    MB64_BUTTON_FORMATION,
    MB64_BUTTON_VEXCLA,
    MB64_BUTTON_EXCLA,
    MB64_BUTTON_POWER,
    MB64_BUTTON_MASK,
    MB64_BUTTON_BADGE,
    MB64_BUTTON_HEART,
    MB64_BUTTON_SPAWN,

    // objects
    MB64_BUTTON_MPLAT,
    MB64_BUTTON_MPLAT_LOOP,
    MB64_BUTTON_WOODPLAT,
    MB64_BUTTON_CONVEYOR,
    MB64_BUTTON_NOTEBLOCK,
    MB64_BUTTON_PURPLE_SWITCH,
    MB64_BUTTON_TIMED_BOX,
    MB64_BUTTON_TIMED_BLOCK,
    MB64_BUTTON_BUTTON,
    MB64_BUTTON_BLOCK,
    MB64_BUTTON_DIAMOND,
    MB64_BUTTON_BREAKABLE,
    MB64_BUTTON_RFBOX,
    MB64_BUTTON_SMALL_BOX,
    MB64_BUTTON_CRAZY_BOX,
    MB64_BUTTON_FIRE,
    MB64_BUTTON_BLUE_FLAME,
    MB64_BUTTON_FIRE_SPINNER,
    MB64_BUTTON_FIRE_SPITTER,
    MB64_BUTTON_FLAMETHROWER,
    MB64_BUTTON_SIGN,
    MB64_BUTTON_BUDDY,
    MB64_BUTTON_TOAD,
    MB64_BUTTON_TUXIE,
    MB64_BUTTON_UKIKI,
    MB64_BUTTON_MOLEMAN,
    MB64_BUTTON_COBIE,
    MB64_BUTTON_KTQ,

    // enemies
    MB64_BUTTON_GOOMBA,
    MB64_BUTTON_BIG_GOOMBA,
    MB64_BUTTON_TINY_GOOMBA,
    MB64_BUTTON_PIRANHA,
    MB64_BUTTON_BIG_PIRANHA,
    MB64_BUTTON_TINY_PIRANHA,
    MB64_BUTTON_KOOPA,
    MB64_BUTTON_BOBOMB,
    MB64_BUTTON_CHUCKYA,
    MB64_BUTTON_MOTOS,
    MB64_BUTTON_HEAVEHO,
    MB64_BUTTON_BULLET,
    MB64_BUTTON_BBALL,
    MB64_BUTTON_LAKITU,
    MB64_BUTTON_FLYGUY,
    MB64_BUTTON_SNUFIT,
    MB64_BUTTON_AMP,
    MB64_BUTTON_BULLY,
    MB64_BUTTON_CHILL_BULLY,
    MB64_BUTTON_BIG_BULLY,
    MB64_BUTTON_CHIEF_CHILLY,
    MB64_BUTTON_THWOMP,
    MB64_BUTTON_GRINDEL,
    MB64_BUTTON_WHOMP,
    MB64_BUTTON_SCUTTLEBUG,
    MB64_BUTTON_BOO,
    MB64_BUTTON_MR_I,
    MB64_BUTTON_SPINDRIFT,
    MB64_BUTTON_BLIZZARD,
    MB64_BUTTON_MONEYBAG,
    MB64_BUTTON_SKEETER,
    MB64_BUTTON_POKEY,
    MB64_BUTTON_BOWSER,
    MB64_BUTTON_MINE,
    MB64_BUTTON_KING_BOBOMB,
    MB64_BUTTON_KING_WHOMP,
    MB64_BUTTON_BIG_BOO,
    MB64_BUTTON_WIGGLER,
    MB64_BUTTON_REX,
    MB64_BUTTON_HAMMER_BRO,
    MB64_BUTTON_FIRE_BRO,
    MB64_BUTTON_PODOBOO,
    MB64_BUTTON_PHANTASM,
    MB64_BUTTON_CHICKEN,
    MB64_BUTTON_CRABLET,
    MB64_BUTTON_SHOWRUN,

    MB64_BUTTON_PIPE,
    MB64_BUTTON_BLANK,

    MB64_LEAF_COUNT,
    // folders (toolbox only)
    MB64_FOLDER_GENTLE_SLOPES = MB64_LEAF_COUNT,
    MB64_FOLDER_SLOPES,
    MB64_FOLDER_PLATFORMS,
    MB64_FOLDER_SWITCHES,
    MB64_FOLDER_BOXES,
    MB64_FOLDER_FIRE,
    MB64_FOLDER_POWER_STARS,
    MB64_FOLDER_COINS,
    MB64_FOLDER_POWERUPS,
    MB64_FOLDER_NPCS,
    MB64_FOLDER_GENERIC_ENEMIES,
    MB64_FOLDER_BULLIES,
    MB64_FOLDER_MECHANICAL_ENEMIES,
    MB64_FOLDER_MISC_ENEMIES,
    MB64_FOLDER_SLABS,
    MB64_FOLDER_STONE_ENEMIES,
    MB64_FOLDER_FLYING_ENEMIES,
    MB64_FOLDER_VANILLA_BOSSES,
    MB64_FOLDER_DIAGONAL_SLOPES,
    MB64_FOLDER_SPECIAL_TILES,
    MB64_FOLDER_BTCM_ENEMIES,
    MB64_FOLDER_BTCM_BOSSES,

    MB64_BUTTON_COUNT,
};

#define MB64_FOLDER_MAX_CHILDREN 9
#define MB64_FOLDER_COUNT (MB64_BUTTON_COUNT - MB64_LEAF_COUNT)
#define MB64_TOOLBAR_SIZE 9
#define MB64_TOOLBOX_COLUMNS 9
#define MB64_TOOLBOX_ROWS 4
#define MB64_TOOLBOX_SIZE (MB64_TOOLBOX_COLUMNS * MB64_TOOLBOX_ROWS)

// same-object parameter variants for a leaf button
struct mb64_ui_param {
    const char *name;
    const struct ci_texture_define *btn; // null -> leaf default texture
    u8 bparam;
};

struct mb64_folder_child {
    u8 buttonId;
    u8 gameMask;
};

struct mb64_ui_button_type {
    u8 placeMode; // MB64_PM_NONE = folder
    u8 count; // param count (leaf) or child count (folder)
    union {
        struct {
            u32 id;
            const struct mb64_ui_param *params;
        } leaf;
        struct {
            const char *label;
            const struct mb64_folder_child *children;
            const struct ci_texture_define *icon;
        } folder;
    };
};

extern struct mb64_ui_button_type mb64_ui_buttons[MB64_BUTTON_COUNT];
extern u8 mb64_toolbox_layout_vanilla[MB64_TOOLBOX_SIZE];
extern u8 mb64_toolbox_layout_btcm[MB64_TOOLBOX_SIZE];

extern u8 mb64_toolbar[MB64_TOOLBAR_SIZE];
extern u8 mb64_toolbar_params[MB64_TOOLBAR_SIZE];

extern u8 mb64_toolbar_defaults[MB64_TOOLBAR_SIZE];

extern AnimatedComponent *gToolbar;

void create_toolbar(void);
void show_toolbar(void);
void hide_toolbar(void);
void toolbar_set_active(int active);

void create_toolbox(void);
void init_toolbox(void);
void reset_toolbox_state(void);
