extern const GeoLayout endflames_geo[];
extern Lights1 endflames_flames_lights;
extern u8 endflames_WorldEndFlames_ci8[];
extern u8 endflames_WorldEndFlames_ci8_pal_rgba16[];
extern Vtx endflames_Cylinder_011_mesh_layer_5_vtx_cull[8];
extern Vtx endflames_Cylinder_011_mesh_layer_5_vtx_0[48];
extern Gfx endflames_Cylinder_011_mesh_layer_5_tri_0[];
extern Gfx mat_endflames_flames[];
extern Gfx mat_revert_endflames_flames[];
extern Gfx endflames_Cylinder_011_mesh_layer_5[];
extern Gfx endflames_material_revert_render_settings[];
