extern const GeoLayout dementor_geo[];
extern Lights1 dementor_Hood_lights;
extern Vtx dementor_root_mesh_layer_1_vtx_0[16];
extern Gfx dementor_root_mesh_layer_1_tri_0[];
extern Vtx dementor_head_mesh_layer_1_vtx_0[88];
extern Gfx dementor_head_mesh_layer_1_tri_0[];
extern Vtx dementor_head_mesh_layer_1_vtx_1[10];
extern Gfx dementor_head_mesh_layer_1_tri_1[];
extern Gfx mat_dementor_Hood[];
extern Gfx mat_dementor_Darkness[];
extern Gfx dementor_root_mesh_layer_1[];
extern Gfx dementor_head_mesh_layer_1[];
extern Gfx dementor_material_revert_render_settings[];
