extern const GeoLayout thwompking_switch_opt1[];
extern const GeoLayout thwompking_switch_opt2[];
extern const GeoLayout thwompking_geo[];
extern Lights1 thwompking_ThwompKingBody_lights;
extern Lights1 thwompking_ThwompFace1_lights;
extern Lights1 thwompking_Crown_lights;
extern Lights1 thwompking_Robe_lights;
extern Lights1 thwompking_ThwompFace2_lights;
extern Lights1 thwompking_ThwompFace3_lights;
extern u8 thwompking_ThwompKing_Body_i8[];
extern u8 thwompking_Thwompking_1_rgba16[];
extern u8 thwompking_Crown_ci8[];
extern u8 thwompking_Crown_ci8_pal_rgba16[];
extern u8 thwompking_Robe_ci8[];
extern u8 thwompking_Robe_ci8_pal_rgba16[];
extern u8 thwompking_Thwompking_2_rgba16[];
extern u8 thwompking_ThwompKing_3_rgba16[];
extern Vtx thwompking_dl_mesh_layer_1_vtx_0[48];
extern Gfx thwompking_dl_mesh_layer_1_tri_0[];
extern Vtx thwompking_dl_mesh_layer_1_vtx_1[4];
extern Gfx thwompking_dl_mesh_layer_1_tri_1[];
extern Vtx thwompking_dl_mesh_layer_1_vtx_2[30];
extern Gfx thwompking_dl_mesh_layer_1_tri_2[];
extern Vtx thwompking_dl_mesh_layer_1_vtx_3[36];
extern Gfx thwompking_dl_mesh_layer_1_tri_3[];
extern Gfx mat_thwompking_ThwompKingBody[];
extern Gfx mat_thwompking_ThwompFace1[];
extern Gfx mat_thwompking_Crown[];
extern Gfx mat_revert_thwompking_Crown[];
extern Gfx mat_thwompking_Robe[];
extern Gfx mat_revert_thwompking_Robe[];
extern Gfx mat_thwompking_ThwompFace2[];
extern Gfx mat_thwompking_ThwompFace3[];
extern Gfx thwompking_dl_mesh_layer_1[];
extern Gfx thwompking_dl_mesh_layer_1_mat_override_ThwompFace2_0[];
extern Gfx thwompking_dl_mesh_layer_1_mat_override_ThwompFace3_1[];
extern Gfx thwompking_material_revert_render_settings[];
