#include "src/game/envfx_snow.h"

const GeoLayout Rex_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 15, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 65536),
			GEO_SHADOW(1, 200, 100),
			GEO_CULLING_RADIUS(250),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, -12, 19, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_body_mesh_layer_1_mat_override_redbody_0),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 4, 5, 0, -90, -161),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lleg_mesh_layer_1_mat_override_redbody_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 15, 30, 3, -19, 0, -90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lshoulder_mesh_layer_1_mat_override_redbody_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Larm_skinned_mesh_layer_1_mat_override_redbody_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Larm_mesh_layer_1_mat_override_redbody_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8, 25, -8, -108, -21, -2),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Lwing_mesh_layer_4_mat_override_redbody_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 4, 5, 0, -90, -161),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rleg_mesh_layer_1_mat_override_redbody_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 30, 3, 71, 0, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rshoulder_mesh_layer_1_mat_override_redbody_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Rarm_skinned_mesh_layer_1_mat_override_redbody_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Rarm_mesh_layer_1_mat_override_redbody_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -8, 25, -8, -108, 21, 2),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Rwing_mesh_layer_4_mat_override_redbody_0),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_head_skinned_mesh_layer_1_mat_override_redbody_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, -3, -19, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_head_mesh_layer_1_mat_override_redbody_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, -123, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Rex_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 15, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 65536),
			GEO_SHADOW(1, 200, 100),
			GEO_CULLING_RADIUS(250),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, -12, 19, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_body_mesh_layer_1_mat_override_metal_body_1),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 4, 5, 0, -90, -161),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lleg_mesh_layer_1_mat_override_metal_body_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 15, 30, 3, -19, 0, -90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lshoulder_mesh_layer_1_mat_override_metal_body_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Larm_skinned_mesh_layer_1_mat_override_metal_body_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Larm_mesh_layer_1_mat_override_metal_body_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8, 25, -8, -108, -21, -2),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Lwing_mesh_layer_4_mat_override_metal_body_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 4, 5, 0, -90, -161),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rleg_mesh_layer_1_mat_override_metal_body_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 30, 3, 71, 0, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rshoulder_mesh_layer_1_mat_override_metal_body_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Rarm_skinned_mesh_layer_1_mat_override_metal_body_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Rarm_mesh_layer_1_mat_override_metal_body_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -8, 25, -8, -108, 21, 2),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Rwing_mesh_layer_4_mat_override_metal_body_1),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_head_skinned_mesh_layer_1_mat_override_metal_body_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, -3, -19, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_head_mesh_layer_1_mat_override_metal_body_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, -123, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rex_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 15, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_OPAQUE, 65536),
					GEO_SHADOW(1, 200, 100),
					GEO_CULLING_RADIUS(250),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, -12, 19, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_body_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 4, 5, 0, -90, -161),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lleg_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 15, 30, 3, -19, 0, -90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Lshoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Larm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Larm_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8, 25, -8, -108, -21, -2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Lwing_mesh_layer_4),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 4, 5, 0, -90, -161),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rleg_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 30, 3, 71, 0, 90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_Rshoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_Rarm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, Rex_Rarm_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -8, 25, -8, -108, 21, 2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, Rex_Rwing_mesh_layer_4),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_head_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, -3, -19, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Rex_head_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, -123, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, Rex_switch_opt1),
			GEO_BRANCH(1, Rex_switch_opt2),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, Rex_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, Rex_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
