extern const GeoLayout bdoor_geo[];
extern Lights1 bdoor_Wooden_Door_lights;
extern Lights1 bdoor_Wood_Flooring_lights;
extern u8 bdoor_Wooden_Door_i8[];
extern u8 bdoor_house_floor_i8[];
extern Vtx bdoor_door_mesh_layer_1_vtx_cull[8];
extern Vtx bdoor_door_mesh_layer_1_vtx_0[18];
extern Gfx bdoor_door_mesh_layer_1_tri_0[];
extern Vtx bdoor_door_mesh_layer_1_vtx_1[20];
extern Gfx bdoor_door_mesh_layer_1_tri_1[];
extern Gfx mat_bdoor_Wooden_Door[];
extern Gfx mat_revert_bdoor_Wooden_Door[];
extern Gfx mat_bdoor_Wood_Flooring[];
extern Gfx mat_revert_bdoor_Wood_Flooring[];
extern Gfx bdoor_door_mesh_layer_1[];
extern Gfx bdoor_material_revert_render_settings[];
