extern const GeoLayout badge_geo[];
extern u8 badge_glow_ia8[];
extern Vtx badge_ability_unlock_mesh_layer_5_vtx_0[4];
extern Gfx badge_ability_unlock_mesh_layer_5_tri_0[];
extern Vtx badge_ability_unlock_mesh_layer_5_vtx_1[13];
extern Gfx badge_ability_unlock_mesh_layer_5_tri_1[];
extern Gfx mat_badge_glow[];
extern Gfx mat_revert_badge_glow[];
extern Gfx mat_badge_glow_scroll[];
extern Gfx mat_revert_badge_glow_scroll[];
extern Gfx badge_ability_unlock_mesh_layer_5[];
extern Gfx badge_material_revert_render_settings[];
