extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_1_spline_hot_foc[];
extern struct CutsceneSplinePoint bob_area_1_spline_hot_pos[];
extern Lights1 bob_dl_Lava_lights;
extern Lights1 bob_dl_basalt_lights;
extern Lights1 bob_dl_Obsidian_lights;
extern Lights1 bob_dl_brick_lights;
extern Lights1 bob_dl_pattern_lights;
extern Lights1 bob_dl_gake_lights;
extern Lights1 bob_dl_pillar_lights;
extern Lights1 bob_dl_darkgate_lights;
extern Lights1 bob_dl_carpet_lights;
extern Lights1 bob_dl_Sky_layer0_lights;
extern Lights1 bob_dl_rope_lights;
extern Lights1 bob_dl_Grid_lights;
extern u8 bob_dl_yogan01_rgba16[];
extern u8 bob_dl_basalt_ci8[];
extern u8 bob_dl_basalt_ci8_pal_rgba16[];
extern u8 bob_dl_Obsidian_i8[];
extern u8 bob_dl_Monobrick_i4[];
extern u8 bob_dl_Pattern_i4[];
extern u8 bob_dl_dark_gake_i8[];
extern u8 bob_dl_Pillar_i8[];
extern u8 bob_dl_DarkGate_i8[];
extern u8 bob_dl_Carpet_ci8[];
extern u8 bob_dl_Carpet_ci8_pal_rgba16[];
extern u8 bob_dl_Rope_rgba16[];
extern u8 bob_dl_Transgate_ia8[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_0[70];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_0[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_1[895];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_1[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_2[375];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_2[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_3[1301];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_3[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_4[510];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_4[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_5[461];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_5[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_6[522];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_6[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_7[78];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_7[];
extern Vtx bob_dl_a1_lev_geo_col_mesh_vtx_8[8];
extern Gfx bob_dl_a1_lev_geo_col_mesh_tri_8[];
extern Vtx bob_dl_aSky_mesh_layer_0_vtx_0[16];
extern Gfx bob_dl_aSky_mesh_layer_0_tri_0[];
extern Vtx bob_dl_non_solid_mesh_vtx_0[250];
extern Gfx bob_dl_non_solid_mesh_tri_0[];
extern Vtx bob_dl_non_solid_mesh_vtx_1[8];
extern Gfx bob_dl_non_solid_mesh_tri_1[];
extern Vtx bob_dl_Rope_mesh_vtx_0[15];
extern Gfx bob_dl_Rope_mesh_tri_0[];
extern Vtx bob_dl_Rope_001_mesh_vtx_0[15];
extern Gfx bob_dl_Rope_001_mesh_tri_0[];
extern Vtx bob_dl_Zgrate_mesh_vtx_0[24];
extern Gfx bob_dl_Zgrate_mesh_tri_0[];
extern Gfx mat_bob_dl_Lava[];
extern Gfx mat_bob_dl_basalt[];
extern Gfx mat_revert_bob_dl_basalt[];
extern Gfx mat_bob_dl_Obsidian[];
extern Gfx mat_bob_dl_brick[];
extern Gfx mat_revert_bob_dl_brick[];
extern Gfx mat_bob_dl_pattern[];
extern Gfx mat_bob_dl_gake[];
extern Gfx mat_revert_bob_dl_gake[];
extern Gfx mat_bob_dl_pillar[];
extern Gfx mat_bob_dl_darkgate[];
extern Gfx mat_bob_dl_carpet[];
extern Gfx mat_revert_bob_dl_carpet[];
extern Gfx mat_bob_dl_Sky_layer0[];
extern Gfx mat_revert_bob_dl_Sky_layer0[];
extern Gfx mat_bob_dl_rope[];
extern Gfx mat_bob_dl_Grid[];
extern Gfx bob_dl_a1_lev_geo_col_mesh[];
extern Gfx bob_dl_aSky_mesh_layer_0[];
extern Gfx bob_dl_non_solid_mesh[];
extern Gfx bob_dl_Rope_mesh[];
extern Gfx bob_dl_Rope_001_mesh[];
extern Gfx bob_dl_Zgrate_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];
