extern const GeoLayout showrunner_tv_angry_geo[];
extern Lights1 showrunner_tv_angry_backroom_lights;
extern u8 showrunner_tv_angry_angry_ci4[];
extern u8 showrunner_tv_angry_angry_ci4_pal_rgba16[];
extern u8 showrunner_tv_angry_Backroom_Blw_i8[];
extern Vtx showrunner_tv_angry_visual_003_mesh_layer_1_vtx_0[4];
extern Gfx showrunner_tv_angry_visual_003_mesh_layer_1_tri_0[];
extern Vtx showrunner_tv_angry_visual_003_mesh_layer_1_vtx_1[30];
extern Gfx showrunner_tv_angry_visual_003_mesh_layer_1_tri_1[];
extern Gfx mat_showrunner_tv_angry_angry[];
extern Gfx mat_revert_showrunner_tv_angry_angry[];
extern Gfx mat_showrunner_tv_angry_backroom[];
extern Gfx mat_revert_showrunner_tv_angry_backroom[];
extern Gfx showrunner_tv_angry_visual_003_mesh_layer_1[];
extern Gfx showrunner_tv_angry_material_revert_render_settings[];
