extern const GeoLayout sr_statue_geo[];
extern Lights1 sr_statue_Stone_lights;
extern u8 sr_statue_Concrete_ci4[];
extern u8 sr_statue_Concrete_ci4_pal_rgba16[];
extern u8 sr_statue_small_metal_rgba16[];
extern Vtx sr_statue_ShowrunnerStatue_002_mesh_layer_1_vtx_0[614];
extern Gfx sr_statue_ShowrunnerStatue_002_mesh_layer_1_tri_0[];
extern Vtx sr_statue_ShowrunnerStatue_002_mesh_layer_1_vtx_1[11];
extern Gfx sr_statue_ShowrunnerStatue_002_mesh_layer_1_tri_1[];
extern Gfx mat_sr_statue_Stone[];
extern Gfx mat_revert_sr_statue_Stone[];
extern Gfx mat_sr_statue_seed[];
extern Gfx mat_revert_sr_statue_seed[];
extern Gfx sr_statue_ShowrunnerStatue_002_mesh_layer_1[];
extern Gfx sr_statue_material_revert_render_settings[];
