// 0x05008D14
const GeoLayout manta_seg5_geo_05008D14[] = {
    GEO_SCALE(0, 16384),
    GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
      GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05006750),
        GEO_OPEN_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 440, 220, 6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05005358),
            GEO_OPEN_NODE(),
              GEO_ANIMATED_PART(LAYER_OPAQUE, 220, 0, 0, manta_seg5_dl_050055A8),
              GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 180, 0, 0, manta_seg5_dl_05005768),
              GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 440, -220, 6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05005C38),
            GEO_OPEN_NODE(),
              GEO_ANIMATED_PART(LAYER_OPAQUE, 220, 0, 0, manta_seg5_dl_05005E88),
              GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 180, 0, 0, manta_seg5_dl_05006048),
              GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05006C08),
            GEO_OPEN_NODE(),
              GEO_ANIMATED_PART(LAYER_OPAQUE, 168, 0, 0, manta_seg5_dl_05006B70),
              GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 0, 0, manta_seg5_dl_05006B08),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 0, 0, manta_seg5_dl_05004E90),
              GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 688, 120, -6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05005038),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 668, 170, 6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05004DB8),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 688, -120, -6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05005918),
          GEO_CLOSE_NODE(),
          GEO_ANIMATED_PART(LAYER_OPAQUE, 668, -170, 6, NULL),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, manta_seg5_dl_05004A70),
          GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
