extern const GeoLayout onoffblock2_000_switch_opt1[];
extern const GeoLayout onoffblock2_geo[];
extern Lights1 onoffblock2_redblock_lights;
extern Lights1 onoffblock2_blueblock_lights;
extern u8 onoffblock2_redbox_ci8[];
extern u8 onoffblock2_redbox_ci8_pal_rgba16[];
extern u8 onoffblock2_bluebox_ci8[];
extern u8 onoffblock2_bluebox_ci8_pal_rgba16[];
extern Vtx onoffblock2_000_displaylist_mesh_layer_1_vtx_0[18];
extern Gfx onoffblock2_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_onoffblock2_redblock[];
extern Gfx mat_revert_onoffblock2_redblock[];
extern Gfx mat_onoffblock2_blueblock[];
extern Gfx mat_revert_onoffblock2_blueblock[];
extern Gfx onoffblock2_000_displaylist_mesh_layer_1[];
extern Gfx onoffblock2_000_displaylist_mesh_layer_1_mat_override_blueblock_0[];
extern Gfx onoffblock2_material_revert_render_settings[];
