extern const GeoLayout new_cull_marker_geo[];
extern Lights1 new_cull_marker_red_lights;
extern Lights1 new_cull_marker_black_lights;
extern Vtx new_cull_marker_Plane_mesh_layer_1_vtx_0[20];
extern Gfx new_cull_marker_Plane_mesh_layer_1_tri_0[];
extern Vtx new_cull_marker_Plane_mesh_layer_1_vtx_1[48];
extern Gfx new_cull_marker_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_new_cull_marker_red[];
extern Gfx mat_new_cull_marker_black[];
extern Gfx new_cull_marker_Plane_mesh_layer_1[];
extern Gfx new_cull_marker_material_revert_render_settings[];
