extern const GeoLayout imbuec_geo[];
extern Vtx imbuec_imbue_star_001_mesh_layer_7_vtx_0[48];
extern Gfx imbuec_imbue_star_001_mesh_layer_7_tri_0[];
extern Vtx imbuec_imbue_star_001_mesh_layer_7_vtx_1[78];
extern Gfx imbuec_imbue_star_001_mesh_layer_7_tri_1[];
extern Gfx mat_imbuec_noz_dynamic[];
extern Gfx mat_revert_imbuec_noz_dynamic[];
extern Gfx mat_imbuec_noz_black[];
extern Gfx mat_revert_imbuec_noz_black[];
extern Gfx imbuec_imbue_star_001_mesh_layer_7[];
