extern const GeoLayout mill_geo[];
extern Lights1 mill_ShadedWood_lights;
extern u8 mill_Alternate_Wood_ci8[];
extern u8 mill_Alternate_Wood_ci8_pal_rgba16[];
extern Vtx mill_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx mill_Cube_002_mesh_layer_1_vtx_0[344];
extern Gfx mill_Cube_002_mesh_layer_1_tri_0[];
extern Gfx mat_mill_ShadedWood[];
extern Gfx mat_revert_mill_ShadedWood[];
extern Gfx mill_Cube_002_mesh_layer_1[];
extern Gfx mill_material_revert_render_settings[];
