extern const GeoLayout rr_door_geo[];
extern Lights1 rr_door_Warning2_lights;
extern Lights1 rr_door_Door_lights;
extern u8 rr_door_Warning2_ci8[];
extern u8 rr_door_Warning2_ci8_pal_rgba16[];
extern u8 rr_door_Door_i8[];
extern Vtx rr_door_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx rr_door_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx rr_door_Cube_001_mesh_layer_1_tri_0[];
extern Vtx rr_door_Cube_001_mesh_layer_1_vtx_1[42];
extern Gfx rr_door_Cube_001_mesh_layer_1_tri_1[];
extern Gfx mat_rr_door_Warning2[];
extern Gfx mat_revert_rr_door_Warning2[];
extern Gfx mat_rr_door_Door[];
extern Gfx mat_revert_rr_door_Door[];
extern Gfx rr_door_Cube_001_mesh_layer_1[];
extern Gfx rr_door_material_revert_render_settings[];
