extern const GeoLayout onoffblock3_000_switch_opt1[];
extern const GeoLayout onoffblock3_geo[];
extern Lights1 onoffblock3_excla_blue_lights;
extern Lights1 onoffblock3_excla_red_lights;
extern u8 onoffblock3_bluebox2_ci8[];
extern u8 onoffblock3_bluebox2_pal_rgba16[];
extern u8 onoffblock3_redbox2_ci8[];
extern u8 onoffblock3_redbox2_pal_rgba16[];
extern Vtx onoffblock3_000_displaylist_mesh_layer_1_vtx_0[87];
extern Gfx onoffblock3_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_onoffblock3_excla_blue[];
extern Gfx mat_revert_onoffblock3_excla_blue[];
extern Gfx mat_onoffblock3_excla_red[];
extern Gfx mat_revert_onoffblock3_excla_red[];
extern Gfx onoffblock3_000_displaylist_mesh_layer_1[];
extern Gfx onoffblock3_000_displaylist_mesh_layer_1_mat_override_excla_red_0[];
extern Gfx onoffblock3_material_revert_render_settings[];
