extern const GeoLayout denormO_geo[];
extern Lights1 denormO_Denorm_lights;
extern u8 denormO_Denorm_ci8[];
extern u8 denormO_Denorm_ci8_pal_rgba16[];
extern Vtx denormO_root_mesh_layer_1_vtx_0[42];
extern Gfx denormO_root_mesh_layer_1_tri_0[];
extern Vtx denormO_arm_mesh_layer_1_vtx_0[68];
extern Gfx denormO_arm_mesh_layer_1_tri_0[];
extern Vtx denormO_head_mesh_layer_1_vtx_0[227];
extern Gfx denormO_head_mesh_layer_1_tri_0[];
extern Gfx mat_denormO_Denorm[];
extern Gfx mat_revert_denormO_Denorm[];
extern Gfx denormO_root_mesh_layer_1[];
extern Gfx denormO_arm_mesh_layer_1[];
extern Gfx denormO_head_mesh_layer_1[];
extern Gfx denormO_material_revert_render_settings[];
