extern const GeoLayout garage_geo[];
extern Lights1 garage_garage_lights;
extern Lights1 garage__10_star_door_lights;
extern u8 garage_Silo_i8[];
extern u8 garage__10_star_door_ci8[];
extern u8 garage__10_star_door_ci8_pal_rgba16[];
extern Vtx garage_Cube_011_mesh_layer_1_vtx_0[4];
extern Gfx garage_Cube_011_mesh_layer_1_tri_0[];
extern Vtx garage_Cube_011_mesh_layer_4_vtx_0[4];
extern Gfx garage_Cube_011_mesh_layer_4_tri_0[];
extern Gfx mat_garage_garage[];
extern Gfx mat_garage__10_star_door[];
extern Gfx mat_revert_garage__10_star_door[];
extern Gfx garage_Cube_011_mesh_layer_1[];
extern Gfx garage_Cube_011_mesh_layer_4[];
extern Gfx garage_material_revert_render_settings[];
