extern const GeoLayout imbue_geo[];
extern Vtx imbue_imbue_excla_mesh_layer_7_vtx_0[20];
extern Gfx imbue_imbue_excla_mesh_layer_7_tri_0[];
extern Vtx imbue_imbue_excla_mesh_layer_7_vtx_1[8];
extern Gfx imbue_imbue_excla_mesh_layer_7_tri_1[];
extern Vtx imbue_imbue_excla_mesh_layer_7_vtx_2[40];
extern Gfx imbue_imbue_excla_mesh_layer_7_tri_2[];
extern Gfx mat_imbue_noz_dynamic[];
extern Gfx mat_revert_imbue_noz_dynamic[];
extern Gfx mat_imbue_noz_white[];
extern Gfx mat_revert_imbue_noz_white[];
extern Gfx mat_imbue_noz_black[];
extern Gfx mat_revert_imbue_noz_black[];
extern Gfx imbue_imbue_excla_mesh_layer_7[];
