extern const GeoLayout movie5_geo[];
extern u8 movie5_Projector_Brick_1_i8[];
extern u8 movie5_Projector_Brick_2_ia8[];
extern Vtx movie5_Cube_008_mesh_layer_5_vtx_cull[8];
extern Vtx movie5_Cube_008_mesh_layer_5_vtx_0[116];
extern Gfx movie5_Cube_008_mesh_layer_5_tri_0[];
extern Gfx mat_movie5_ProjectorBrick_layer5[];
extern Gfx mat_revert_movie5_ProjectorBrick_layer5[];
extern Gfx movie5_Cube_008_mesh_layer_5[];
extern Gfx movie5_material_revert_render_settings[];
