extern const GeoLayout agpillar2_geo[];
extern Lights1 agpillar2_BioTechPillar_lights;
extern Lights1 agpillar2_gross_top_lights;
extern u8 agpillar2_biotech_pillar_ci8[];
extern u8 agpillar2_biotech_pillar_ci8_pal_rgba16[];
extern u8 agpillar2_gross_top_ci8[];
extern u8 agpillar2_gross_top_ci8_pal_rgba16[];
extern Vtx agpillar2_Cylinder_008_mesh_layer_1_vtx_cull[8];
extern Vtx agpillar2_Cylinder_008_mesh_layer_1_vtx_0[290];
extern Gfx agpillar2_Cylinder_008_mesh_layer_1_tri_0[];
extern Vtx agpillar2_Cylinder_008_mesh_layer_1_vtx_1[88];
extern Gfx agpillar2_Cylinder_008_mesh_layer_1_tri_1[];
extern Gfx mat_agpillar2_BioTechPillar[];
extern Gfx mat_revert_agpillar2_BioTechPillar[];
extern Gfx mat_agpillar2_gross_top[];
extern Gfx mat_revert_agpillar2_gross_top[];
extern Gfx agpillar2_Cylinder_008_mesh_layer_1[];
extern Gfx agpillar2_material_revert_render_settings[];
