extern const GeoLayout gatess_geo[];
extern Lights1 gatess_grate_lights;
extern u8 gatess_Transgate_ia8[];
extern Vtx gatess_SketchUp_001_mesh_layer_4_vtx_cull[8];
extern Vtx gatess_SketchUp_001_mesh_layer_4_vtx_0[12];
extern Gfx gatess_SketchUp_001_mesh_layer_4_tri_0[];
extern Gfx mat_gatess_grate[];
extern Gfx mat_revert_gatess_grate[];
extern Gfx gatess_SketchUp_001_mesh_layer_4[];
extern Gfx gatess_material_revert_render_settings[];
