// 0x160003A8
const GeoLayout castle_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x1600043C
const GeoLayout cabin_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_cabin_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_cabin_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160004D0
const GeoLayout wooden_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_rough_wooden_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_rough_wooden_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000564
const GeoLayout wooden_door2_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_rough_wooden_door2_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_rough_wooden_door2_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160005F8
const GeoLayout metal_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_metal_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_metal_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x1600068C
const GeoLayout hazy_maze_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_cave_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_cave_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000720
const GeoLayout haunted_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_RENDER_RANGE(-2048, 3500),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_haunted_door_near),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(3500, 32767),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_haunted_door_far),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160007B4
const GeoLayout castle_door_0_star_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
#ifndef AUTO_LOD
               GEO_RENDER_RANGE(-2048, 1000),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, door_seg3_dl_zero_star_near),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(1000, 32767),
#endif
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, door_seg3_dl_zero_star_far),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000868
const GeoLayout castle_door_1_star_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
#ifndef AUTO_LOD
               GEO_RENDER_RANGE(-2048, 1000),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, door_seg3_dl_one_star_near),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(1000, 32767),
#endif
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, door_seg3_dl_one_star_far),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x1600091C
const GeoLayout castle_door_3_stars_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
#ifndef AUTO_LOD
               GEO_RENDER_RANGE(-2048, 1000),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, door_seg3_dl_three_stars_near),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_RENDER_RANGE(1000, 32767),
#endif
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_polished_wooden_door_near),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, door_seg3_dl_three_stars_far),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160009D0
const GeoLayout key_door_geo[] = {
   GEO_TRANSLATE_NODE(0x00, 78, 0, 0),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_key_door),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
