extern const GeoLayout weakgrate_geo[];
extern Lights1 weakgrate_Grate_Side_lights;
extern u8 weakgrate_Fan1_ci8[];
extern u8 weakgrate_Fan1_ci8_pal_rgba16[];
extern u8 weakgrate_Transgate_ia8[];
extern Vtx weakgrate_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx weakgrate_Cube_001_mesh_layer_1_vtx_0[46];
extern Gfx weakgrate_Cube_001_mesh_layer_1_tri_0[];
extern Vtx weakgrate_Cube_001_mesh_layer_4_vtx_cull[8];
extern Vtx weakgrate_Cube_001_mesh_layer_4_vtx_0[4];
extern Gfx weakgrate_Cube_001_mesh_layer_4_tri_0[];
extern Gfx mat_weakgrate_Grate_Side[];
extern Gfx mat_revert_weakgrate_Grate_Side[];
extern Gfx mat_weakgrate_Grate[];
extern Gfx mat_revert_weakgrate_Grate[];
extern Gfx weakgrate_Cube_001_mesh_layer_1[];
extern Gfx weakgrate_Cube_001_mesh_layer_4[];
extern Gfx weakgrate_material_revert_render_settings[];
