extern const GeoLayout agcrack_switch_opt1[];
extern const GeoLayout agcrack_switch_opt2[];
extern const GeoLayout agcrack_geo[];
extern u8 agcrack_Crack1_ia8[];
extern u8 agcrack_TVhead_static_i8[];
extern u8 agcrack_Crack2_ia8[];
extern u8 agcrack_Crack3_ia8[];
extern Vtx agcrack_dl_mesh_layer_5_vtx_0[4];
extern Gfx agcrack_dl_mesh_layer_5_tri_0[];
extern Vtx agcrack_dl_mesh_layer_1_vtx_0[4];
extern Gfx agcrack_dl_mesh_layer_1_tri_0[];
extern Gfx mat_agcrack_Crack[];
extern Gfx mat_agcrack_static_quicksand_001[];
extern Gfx mat_revert_agcrack_static_quicksand_001[];
extern Gfx mat_agcrack_Crack2[];
extern Gfx mat_agcrack_Crack3[];
extern Gfx agcrack_dl_mesh_layer_5[];
extern Gfx agcrack_dl_mesh_layer_5_mat_override_Crack2_0[];
extern Gfx agcrack_dl_mesh_layer_5_mat_override_Crack3_1[];
extern Gfx agcrack_dl_mesh_layer_1[];
extern Gfx agcrack_dl_mesh_layer_1_mat_override_Crack2_0[];
extern Gfx agcrack_dl_mesh_layer_1_mat_override_Crack3_1[];
extern Gfx agcrack_material_revert_render_settings[];
