extern const GeoLayout mic_geo[];
extern Lights1 mic_Microphone_lights;
extern u8 mic_ChainLink_ia8[];
extern u8 mic_rgba16_anonmoose_envmap_silver1_i8[];
extern Vtx mic_Icosphere_mesh_layer_1_vtx_cull[8];
extern Vtx mic_Icosphere_mesh_layer_1_vtx_0[77];
extern Gfx mic_Icosphere_mesh_layer_1_tri_0[];
extern Vtx mic_Icosphere_mesh_layer_1_vtx_1[20];
extern Gfx mic_Icosphere_mesh_layer_1_tri_1[];
extern Gfx mat_mic_Microphone[];
extern Gfx mat_mic_MicMetal[];
extern Gfx mat_revert_mic_MicMetal[];
extern Gfx mic_Icosphere_mesh_layer_1[];
extern Gfx mic_material_revert_render_settings[];
