extern const GeoLayout amp_eletricity_geolayout[];
extern const GeoLayout dAmpGeo[];
extern u8 amp_amp_mouth_rgba16[];
extern u8 amp_amp_eyes_rgba16[];
extern u8 amp_amp_body_rgba16[];
extern u8 amp_amp_electricity_rgba16[];
extern Vtx amp_root_mesh_layer_4_vtx_0[4];
extern Vtx amp_root_mesh_layer_4_vtx_1[4];
extern Vtx amp_billboard_mesh_layer_4_vtx_0[4];
extern Vtx amp_switch_option_eletricity_mesh_layer_4_vtx_0[5];
extern Vtx amp_switch_option_eletricity_001_mesh_layer_4_vtx_0[5];
extern Vtx amp_switch_option_eletricity_002_mesh_layer_4_vtx_0[5];
extern Vtx amp_switch_option_eletricity_003_mesh_layer_4_vtx_0[5];
extern Gfx amp_root_mesh_layer_4[];
extern Gfx amp_billboard_mesh_layer_4[];
extern Gfx amp_switch_option_eletricity_mesh_layer_4[];
extern Gfx amp_switch_option_eletricity_001_mesh_layer_4[];
extern Gfx amp_switch_option_eletricity_002_mesh_layer_4[];
extern Gfx amp_switch_option_eletricity_003_mesh_layer_4[];
extern Gfx amp_material_revert_render_settings[];
