extern const GeoLayout wheelo_geo[];
extern Lights1 wheelo_tire_lights;
extern u8 wheelo_Wheel_ci8[];
extern u8 wheelo_Wheel_ci8_pal_rgba16[];
extern Vtx wheelo_Cube_002_mesh_layer_4_vtx_cull[8];
extern Vtx wheelo_Cube_002_mesh_layer_4_vtx_0[8];
extern Gfx wheelo_Cube_002_mesh_layer_4_tri_0[];
extern Gfx mat_wheelo_tire[];
extern Gfx mat_revert_wheelo_tire[];
extern Gfx wheelo_Cube_002_mesh_layer_4[];
extern Gfx wheelo_material_revert_render_settings[];
