extern const GeoLayout pipe2_ccm_geo[];
extern Lights1 pipe2_ccm_Pipe_001_lights;
extern u8 pipe2_ccm_MetalTile_i8[];
extern Vtx pipe2_ccm_Pipe_004_mesh_vtx_cull[8];
extern Vtx pipe2_ccm_Pipe_004_mesh_vtx_0[158];
extern Gfx pipe2_ccm_Pipe_004_mesh_tri_0[];
extern Gfx mat_pipe2_ccm_Pipe_001[];
extern Gfx mat_revert_pipe2_ccm_Pipe_001[];
extern Gfx pipe2_ccm_Pipe_004_mesh[];
extern Gfx pipe2_ccm_material_revert_render_settings[];
