COURSE_ACTS(COURSE_BOB, _(" 1 RED-HOT RESERVOIR"),
       _("THE MIMIC STARS"), _("RED COIN BLAST")     , _("CLIMB UP THE LAVAFALL"),
       _("STEEL CRATE CLEANUP")  , _("TIMED RING CHALLENGE"), _("THE SEARCH FOR 100 COINS"), _("KING BULLY BATTLE"))

CASTLE_SECRET_STARS(_("   SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
