COURSE_ACTS(COURSE_BOB, _(" 1 RED-HOT RESERVOIR"),
       _("THE MIMIC STARS"), _("RED COIN BLAST")     , _("CLIMB UP THE LAVAFALL"),
       _("STEEL CRATE CLEANUP")  , _("TIMED RING CHALLENGE"), _("THE SEARCH FOR 100 COINS"), _("KING BULLY BATTLE"))

COURSE_ACTS(COURSE_WF, _(" 2 LONELY FLOATING FARM"),
       _("UNEARTH THE PIRANHA WEEDS")        , _("TO THE TOP OF THE BARN")    , _("DOWN THE SILO SLIDE"),
       _("PUT THE PIG TO SLEEP"), _("HORSE RIDIN' RINGS")    , _("FARMER'S LOOSE CHANGE"), _("REMATCH WITH THE HOG"))

COURSE_ACTS(COURSE_JRB, _(" 3 JURASSIC SAVANNA"),
       _("THE 5 YOSHI COINS")    , _("TOP OF THE MOUNTAIN") , _("FREE THE VILLAGE"),
       _("SKYWARD SNAKEBLOCK")  , _("FRANTIC ROCKET RINGS")     , _("100 PREHISTORIC COINS"),_("THE DEATH POKEY"))

//courses are swaped!
COURSE_ACTS(COURSE_CCM, _(" 4 THE PHANTOM STRIDER"),
       _("TOP OF THE MAIN MAST"), _("8 REDS OF THE LOST SEA") , _("WALK THE GHOSTLY PLANKS"),
       _("SLIPPERY SNAKE BLOCK"), /*_("THE GOBLET OF SEA MEN")*/ _("THE GHOST'S GOBLET") , _("100 SEA SICK COINS"),_("NAVAL WARFARE"))

COURSE_ACTS(COURSE_BBH, _(" 5 VIRTUAPLEX"),
       _("LEAPING ACROSS THE ROOFTOPS")             , _("DOWN THE SEPTIC SLIDE")             , _("CRATES AND BUTTONS"),
       _("MEDIEVAL COLOSSEUM TRIALS")  , _("DIGITAL VORTEX OF DEATH")     , _("100 BYTECOINS"), _("THE EXECUTIVE"))

COURSE_ACTS(COURSE_HMC, _(" 6 COWBOY CANYON"),
       _("EYE OUT FOR TUMBLING BOULDERS")  , _("COASTING BY WITH THE B.BILL MASK")       , _("REDS OF THE PROSPECTOR'S CAVE"),
       _("PROSPECTOR'S HOT ROPE JUMP")     , _("BANDIT BEATDOWN")     , _("THE COLLECTION OF SCRIP"),_("THE GREAT TRAIN ROBBERY"))

COURSE_ACTS(COURSE_LLL, _(" 7 IMMENSE RESIDENCE"),
       _("QUEST FOR CHEESE")            , _("RED COINS OF THE LIVING ROOM")             , _("GOLD FRIED ONION RINGS"),
       _("LAUNDRY DAY")           , _("FIRE!")  , _("GIANT'S LOOSE CHANGE"),_("VACCUM CHASE"))

COURSE_ACTS(COURSE_SSL, _(" 8 RETROLAND"),
       _("PIPE DREAM") , _("SCALING MUSHROOM MOUNTAIN")      , _("SHELL SURFING AND THWOMP RIDING"),
       _("THE HEAT BELOW THE ICE"), _("THE POINT OF THE MASK")   , _("1-UP TIME"),_("BIT SIZED BOWSER"))

COURSE_ACTS(COURSE_DDD, _(" 9 THWOMP TOWERS"),
       _("DUEL THE THWOMP KING")            , _("RINGS UPON THE TOWER PEAKS")         , _("SHELL RIDE UP THE LAVA FOUNTAIN"),
       _("DOGFIGHT WITH THE WHOMP KING")        , _("SNAKE BLOCK MUTINY")        , _("TREASURE OF THWOMPKIND"),_("ATTACK OF THE THWOMP QUEEN"))

COURSE_ACTS(COURSE_SL, _(" 10 BLUEBERG"),
       _("ATOP THE BUILDING PEAKS")            , _("REDS IN THE SERVERS & CITY")          , _("HEXAGONS IN THE HOLE"),
       _("POWER OF VANETAL")  , _("TUBING DOWN THE TUNNEL") , _("HAMMER BRO HUNDREDS"),_("THE 5000 IQ SUPERQUIZ"))

COURSE_ACTS(COURSE_WDW, _("11 SINFUL STARFAIR"),
       _("FERRIS WHEEL FUN")         , _("THE STAR POWER PLANT")               , _("RED COINS ON MAIN STREET"),
       _("THE FOUR SISTERS")   , _("ROOFTOP RINGS")      , _("EDWARD CONE COINS"),_("CAREFULLY CLIMB THE CONSTRUCTION"))

COURSE_ACTS(COURSE_TTM, _("12 ORCHESTRAL KEYS"),
       _("THE CLIFFS OF SAXAPHONE SKERRY")            , _("SHELL SHREDDIN' THE SUNKEN ROOVES")    , _("SHATTER THE 5 COSMIC ORBS"),
       _("PINK COINS OF THE ISLES")       , _("SECRET PASSAGEWAY TO THE WINDMILL") , _("100 COINS OF THE SOULS WHO PAID"),_("COSMIC ERUPTION"))

COURSE_ACTS(COURSE_THI, _("13 HUSHED HAVEN"),
       _("TOP OF THE TOWN")      , _("PINK COINS ON THE SLOPES"), _("RING GRAFFITI"),
       _("MEMORIZATION OF THE WOODEN HOUSE")       , _("COSMIC SEED IN THE CAGE")           , _("100 BLOCKY COINS"),_("DESTROY THE GOLDEN IDOLS"))

COURSE_ACTS(COURSE_TTC, _("14 THE FINAL EMPIRE"),
       _("JAGGED WALL KICKS TO THE TOP"), _("PINK COINS AROUND THE PARK")     , _("HIGHCANE HEIST"),
       _("SCALE THE BLACKSTONE MOUNTAIN")           , _("THROUGH THE TALL TALL TOWERS")    , _("EMPIRE'S WEALTH"),_("TEMPLE GUARDIAN"))

COURSE_ACTS(COURSE_RR, _("15 TRIALS OF TERMINUS"),
       _("RED TRIAL")  , _("YELLOW TRIAL")      , _("GREEN TRIAL"),
       _("CYAN TRIAL")        , _("BLUE TRIAL") , _("PINK TRIAL"), _("HEART OF AGAMEMNON"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER ON THE HIGHWAY"))
SECRET_STAR(COURSE_BITFS, _("   SHOWDOWN WITH THE SHOWRUNNER"))
SECRET_STAR(COURSE_BITS, _("   -"))
SECRET_STAR(COURSE_PSS, _("   SLOPPY SHELL SEWERS"))
SECRET_STAR(COURSE_COTMC, _("   -"))//metal cap
SECRET_STAR(COURSE_TOTWC, _("   -"))//wing cap
SECRET_STAR(COURSE_VCUTM, _("   -"))//vanish cap
SECRET_STAR(COURSE_WMOTR, _("   LOST CITY"))
SECRET_STAR(COURSE_SA, _("   THE SECRET FACILITY"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
