extern const GeoLayout bits_stairs_geo[];
extern u8 bits_stairs_Projector_Brick_1_i8[];
extern u8 bits_stairs_Projector_Brick_2_ia8[];
extern Vtx bits_stairs_Cube_018_mesh_layer_5_vtx_cull[8];
extern Vtx bits_stairs_Cube_018_mesh_layer_5_vtx_0[223];
extern Gfx bits_stairs_Cube_018_mesh_layer_5_tri_0[];
extern Gfx mat_bits_stairs_ProjectorBrick_layer5[];
extern Gfx mat_revert_bits_stairs_ProjectorBrick_layer5[];
extern Gfx bits_stairs_Cube_018_mesh_layer_5[];
extern Gfx bits_stairs_material_revert_render_settings[];
