extern const GeoLayout puddlepoop_geo[];
extern Lights1 puddlepoop_puddle_lights;
extern u8 puddlepoop_puddle_ci4[];
extern u8 puddlepoop_puddle_ci4_pal_rgba16[];
extern Vtx puddlepoop_Plane_008_mesh_layer_4_vtx_cull[8];
extern Vtx puddlepoop_Plane_008_mesh_layer_4_vtx_0[4];
extern Gfx puddlepoop_Plane_008_mesh_layer_4_tri_0[];
extern Gfx mat_puddlepoop_puddle[];
extern Gfx mat_revert_puddlepoop_puddle[];
extern Gfx puddlepoop_Plane_008_mesh_layer_4[];
extern Gfx puddlepoop_material_revert_render_settings[];
