extern const GeoLayout balloon_geo[];
extern Lights1 balloon_Balloon_lights;
extern u8 balloon_Balloon_ci8[];
extern u8 balloon_Balloon_ci8_pal_rgba16[];
extern Vtx balloon_Plane_mesh_layer_4_vtx_0[4];
extern Gfx balloon_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_balloon_Balloon[];
extern Gfx mat_revert_balloon_Balloon[];
extern Gfx balloon_Plane_mesh_layer_4[];
extern Gfx balloon_material_revert_render_settings[];
