extern const GeoLayout pipe1_ccm_geo[];
extern Lights1 pipe1_ccm_Pipe_001_lights;
extern u8 pipe1_ccm_MetalTile_i8[];
extern u8 pipe1_ccm_poundsymbol_ia8[];
extern Vtx pipe1_ccm_Pipe_002_mesh_vtx_cull[8];
extern Vtx pipe1_ccm_Pipe_002_mesh_vtx_0[136];
extern Gfx pipe1_ccm_Pipe_002_mesh_tri_0[];
extern Vtx pipe1_ccm_Pipe_002_mesh_layer_4_vtx_cull[8];
extern Vtx pipe1_ccm_Pipe_002_mesh_layer_4_vtx_0[8];
extern Gfx pipe1_ccm_Pipe_002_mesh_layer_4_tri_0[];
extern Gfx mat_pipe1_ccm_Pipe_001[];
extern Gfx mat_revert_pipe1_ccm_Pipe_001[];
extern Gfx mat_pipe1_ccm_poundsymbol[];
extern Gfx pipe1_ccm_Pipe_002_mesh[];
extern Gfx pipe1_ccm_Pipe_002_mesh_layer_4[];
extern Gfx pipe1_ccm_material_revert_render_settings[];
