#include "src/game/envfx_snow.h"

const GeoLayout rr_area_0_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, rr_dl_1room1_geo),
			GEO_BRANCH(1, rr_dl_1room2_geo),
			GEO_BRANCH(1, rr_dl_1room3_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rr_dl_1room1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_vis_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_vis_col_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rr_dl_1room2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_earth_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_staticroom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rr_dl_staticroom_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rr_dl_1room3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 22, 0, rr_dl_final_cutscene_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rr_area_0[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_BOSS_FIGHT, 25192, 239, 18758, 25192, 139, 18758, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, rr_area_0_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rr_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
