extern const GeoLayout fatplat_geo[];
extern Lights1 fatplat_woodside_lights;
extern Lights1 fatplat_woodtop_lights;
extern u8 fatplat_woodplatside_ci8[];
extern u8 fatplat_woodplatside_pal_rgba16[];
extern u8 fatplat_woodplattop_ci8[];
extern u8 fatplat_woodplattop_pal_rgba16[];
extern Vtx fatplat_blaster_005_mesh_layer_1_vtx_0[16];
extern Gfx fatplat_blaster_005_mesh_layer_1_tri_0[];
extern Vtx fatplat_blaster_005_mesh_layer_1_vtx_1[8];
extern Gfx fatplat_blaster_005_mesh_layer_1_tri_1[];
extern Gfx mat_fatplat_woodside[];
extern Gfx mat_revert_fatplat_woodside[];
extern Gfx mat_fatplat_woodtop[];
extern Gfx mat_revert_fatplat_woodtop[];
extern Gfx fatplat_blaster_005_mesh_layer_1[];
extern Gfx fatplat_material_revert_render_settings[];
