#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/castle_inside/header.h"

#include "levels/castle_inside/star_door/geo.inc.c"
#include "levels/castle_inside/trap_door/geo.inc.c"
#include "levels/castle_inside/areas/1/geo.inc.c"
#include "levels/castle_inside/areas/2/pendulum/geo.inc.c" // Another weird case
#include "levels/castle_inside/clock_minute_hand/geo.inc.c"
#include "levels/castle_inside/clock_hour_hand/geo.inc.c"
#include "levels/castle_inside/areas/2/geo.inc.c"
#include "levels/castle_inside/water_level_pillar/geo.inc.c"
#include "levels/castle_inside/areas/3/geo.inc.c"
#include "levels/castle_inside/geo.inc.c"

#include "levels/castle_inside/secret_books/geo.inc.c"
#include "levels/castle_inside/reflection_change/geo.inc.c"
#include "levels/castle_inside/fucking_mirror/geo.inc.c"
#include "levels/castle_inside/vr/geo.inc.c"
#include "levels/castle_inside/garage/geo.inc.c"
#include "levels/castle_inside/rocking_chair/geo.inc.c"
#include "levels/castle_inside/ghoad/geo.inc.c"
#include "levels/castle_inside/c5_bridge/geo.inc.c"
#include "levels/castle_inside/book_elevator/geo.inc.c"
#include "levels/castle_inside/tele/geo.inc.c"
#include "levels/castle_inside/mgb/geo.inc.c"
#include "levels/castle_inside/mgb2/geo.inc.c"
#include "levels/castle_inside/grate30/geo.inc.c"
#include "levels/castle_inside/showrunner_tv/geo.inc.c"
#include "levels/castle_inside/dementor/geo.inc.c"
#include "levels/castle_inside/showrunner_tv_angry/geo.inc.c"
#include "levels/castle_inside/phonograph/geo.inc.c"