extern const GeoLayout sb_cube_geo[];
extern Lights1 sb_cube_grid_lights;
extern u8 sb_cube_grid_ia8[];
extern Vtx sb_cube_SelectionBox_mesh_layer_4_vtx_cull[8];
extern Vtx sb_cube_SelectionBox_mesh_layer_4_vtx_0[19];
extern Gfx sb_cube_SelectionBox_mesh_layer_4_tri_0[];
extern Vtx sb_cube_SelectionBox_mesh_layer_4_vtx_1[48];
extern Gfx sb_cube_SelectionBox_mesh_layer_4_tri_1[];
extern Gfx mat_sb_cube_grid[];
extern Gfx mat_revert_sb_cube_grid[];
extern Gfx mat_sb_cube_ZBUFF0_layer4[];
extern Gfx mat_revert_sb_cube_ZBUFF0_layer4[];
extern Gfx sb_cube_SelectionBox_mesh_layer_4[];
extern Gfx sb_cube_material_revert_render_settings[];
