extern const GeoLayout conveyor_geo[];
extern Lights1 conveyor_conveyor_side_lights;
extern Lights1 conveyor_conveyor_top_lights;
extern u8 conveyor_conveyor_side_i8[];
extern u8 conveyor_conveyor_top_ci8[];
extern u8 conveyor_conveyor_top_pal_rgba16[];
extern Vtx conveyor_blaster_007_mesh_layer_1_vtx_0[8];
extern Gfx conveyor_blaster_007_mesh_layer_1_tri_0[];
extern Vtx conveyor_blaster_007_mesh_layer_1_vtx_1[16];
extern Gfx conveyor_blaster_007_mesh_layer_1_tri_1[];
extern Gfx mat_conveyor_conveyor_side[];
extern Gfx mat_conveyor_conveyor_top[];
extern Gfx mat_revert_conveyor_conveyor_top[];
extern Gfx conveyor_blaster_007_mesh_layer_1[];
extern Gfx conveyor_material_revert_render_settings[];
