extern const GeoLayout conveyor_000_switch_opt1[];
extern const GeoLayout conveyor_000_switch_opt2[];
extern const GeoLayout conveyor_geo[];
extern Lights1 conveyor_conveyor_side_lights;
extern Lights1 conveyor_conveyor_top_lights;
extern Lights1 conveyor_conveyor_top_red_lights;
extern Lights1 conveyor_conveyor_top_blue_lights;
extern u8 conveyor_conveyor_side_i8[];
extern u8 conveyor_conveyor_top_rgba16[];
extern u8 conveyor_conveyor_top_red_rgba16[];
extern u8 conveyor_conveyor_top_blue_rgba16[];
extern Vtx conveyor_000_displaylist_mesh_layer_1_vtx_0[8];
extern Gfx conveyor_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx conveyor_000_displaylist_mesh_layer_1_vtx_1[16];
extern Gfx conveyor_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_conveyor_conveyor_side[];
extern Gfx mat_conveyor_conveyor_top[];
extern Gfx mat_conveyor_conveyor_top_red[];
extern Gfx mat_conveyor_conveyor_top_blue[];
extern Gfx conveyor_000_displaylist_mesh_layer_1[];
extern Gfx conveyor_000_displaylist_mesh_layer_1_mat_override_conveyor_top_red_0[];
extern Gfx conveyor_000_displaylist_mesh_layer_1_mat_override_conveyor_top_blue_1[];
extern Gfx conveyor_material_revert_render_settings[];
