#include "actors/conveyor_dslope/texscroll.inc.h"
#include "actors/conveyor/texscroll.inc.h"
#include "actors/conveyor_half/texscroll.inc.h"
#include "actors/conveyor_slope/texscroll.inc.h"
#include "actors/badge/texscroll.inc.h"
#include "actors/mario_btcm/texscroll.inc.h"
//#include "actors/showrunner/texscroll.inc.h"
//#include "actors/egg/texscroll.inc.h"
//#include "actors/chicken/texscroll.inc.h"
//extern void scroll_textures_group_global();
