#include "levels/rr/endflames/texscroll.inc.h"
#include "levels/rr/agmoon/texscroll.inc.h"
#include "levels/rr/agring/texscroll.inc.h"
#include "levels/rr/agwall/texscroll.inc.h"
#include "levels/rr/agcrack/texscroll.inc.h"
#include "levels/rr/blood_particle/texscroll.inc.h"
#include "levels/rr/palamedes/texscroll.inc.h"
#include "levels/rr/blood/texscroll.inc.h"
#include "levels/rr/staticflood/texscroll.inc.h"
#include "levels/rr/rr_tube/texscroll.inc.h"
#include "levels/rr/texscroll.inc.h"
extern void scroll_textures_rr();
