#pragma once

#include "structs.h"

enum {
    TILE_TYPE_EMPTY,
    // Flippable tiles
    TILE_TYPE_SLOPE = 2,
    TILE_TYPE_DSLOPE,
    TILE_TYPE_SLAB,
    TILE_TYPE_DSLAB,
    TILE_TYPE_CORNER,
    TILE_TYPE_DCORNER,
    TILE_TYPE_ICORNER, // Inner Corner
    TILE_TYPE_DICORNER, // Down Inner Corner
    TILE_TYPE_SCORNER, // Sloped Corner
    TILE_TYPE_DSCORNER, // Down Sloped Corner
    TILE_TYPE_ISCORNER, // Inverted Sloped Corner
    TILE_TYPE_DISCORNER, // Down Inverted Sloped Corner
    TILE_TYPE_UGENTLE,
    TILE_TYPE_DUGENTLE,
    TILE_TYPE_LGENTLE,
    TILE_TYPE_DLGENTLE,

    TILE_END_OF_FLIPPABLE,
    TILE_TYPE_BLOCK = TILE_END_OF_FLIPPABLE,
    TILE_TYPE_SSLOPE,
    TILE_TYPE_SSLAB,
    TILE_TYPE_CULL,
    TILE_TYPE_TROLL,
    TILE_TYPE_FENCE,
    TILE_TYPE_POLE,
    TILE_TYPE_BARS,

    TILE_TYPE_WATER, // only blocks that are empty otherwise
};

enum mb64_materials {
    MB64_MATLIST_START,

    // Terrain
    MB64_MAT_GRASS = MB64_MATLIST_START,
    MB64_MAT_GRASS_OLD,
    MB64_MAT_CARTOON_GRASS,
    MB64_MAT_DARK_GRASS,
    MB64_MAT_HMC_GRASS,
    MB64_MAT_ORANGE_GRASS,
    MB64_MAT_RED_GRASS,
    MB64_MAT_PURPLE_GRASS,
    MB64_MAT_SAND,
    MB64_MAT_JRB_SAND,
    MB64_MAT_SNOW,
    MB64_MAT_SNOW_OLD,

    MB64_MAT_DIRT,
    MB64_MAT_SANDDIRT,
    MB64_MAT_LIGHTDIRT,
    MB64_MAT_HMC_DIRT,
    MB64_MAT_ROCKY_DIRT,
    MB64_MAT_DIRT_OLD,
    MB64_MAT_WAVY_DIRT,
    MB64_MAT_WAVY_DIRT_BLUE,
    MB64_MAT_SNOWDIRT,
    MB64_MAT_PURPLE_DIRT,
    MB64_MAT_HMC_LAKEGRASS,

    MB64_MATLIST_TERRAIN_END,

    // Stone
    MB64_MAT_STONE = MB64_MATLIST_TERRAIN_END,
    MB64_MAT_HMC_STONE,
    MB64_MAT_HMC_MAZEFLOOR,
    MB64_MAT_CCM_ROCK,
    MB64_MAT_TTM_FLOOR,
    MB64_MAT_TTM_ROCK,
    MB64_MAT_COBBLESTONE,
    MB64_MAT_JRB_WALL,
    MB64_MAT_GABBRO,
    MB64_MAT_RHR_STONE,
    MB64_MAT_LAVA_ROCKS,
    MB64_MAT_VOLCANO_WALL,
    MB64_MAT_RHR_BASALT,
    MB64_MAT_OBSIDIAN,
    MB64_MAT_CASTLE_STONE,
    MB64_MAT_JRB_UNDERWATER,
    MB64_MAT_SNOW_ROCK,
    MB64_MAT_ICY_ROCK,
    MB64_MAT_DESERT_STONE,
    MB64_MAT_RHR_OBSIDIAN,
    MB64_MAT_JRB_STONE,

    MB64_MATLIST_STONE_END,

    // Bricks
    MB64_MAT_BRICKS = MB64_MATLIST_STONE_END,
    MB64_MAT_DESERT_BRICKS,
    MB64_MAT_RHR_BRICK,
    MB64_MAT_HMC_BRICK,
    MB64_MAT_LIGHTBROWN_BRICK,
    MB64_MAT_WDW_BRICK,
    MB64_MAT_TTM_BRICK,
    MB64_MAT_C_BRICK,
    MB64_MAT_BBH_BRICKS,
    MB64_MAT_ROOF_BRICKS,
    MB64_MAT_C_OUTSIDEBRICK,
    MB64_MAT_SNOW_BRICKS,
    MB64_MAT_JRB_BRICKS,
    MB64_MAT_SNOW_TILE_SIDE,
    MB64_MAT_TILESBRICKS,

    MB64_MATLIST_BRICKS_END,

    // Tiling
    MB64_MAT_TILES = MB64_MATLIST_BRICKS_END,
    MB64_MAT_C_TILES,
    MB64_MAT_DESERT_TILES,
    MB64_MAT_VP_BLUETILES,
    MB64_MAT_SNOW_TILES,
    MB64_MAT_JRB_TILETOP,
    MB64_MAT_JRB_TILESIDE,
    MB64_MAT_HMC_TILES,
    MB64_MAT_GRANITE_TILES,
    MB64_MAT_RHR_TILES,
    MB64_MAT_VP_TILES,
    MB64_MAT_DIAMOND_PATTERN,
    MB64_MAT_C_STONETOP,
    MB64_MAT_SNOW_BRICK_TILES,

    MB64_MATLIST_TILES_END,

    // Cut Stone
    MB64_MAT_DESERT_BLOCK = MB64_MATLIST_TILES_END,
    MB64_MAT_VP_BLOCK,
    MB64_MAT_BBH_STONE,
    MB64_MAT_BBH_STONE_PATTERN,
    MB64_MAT_PATTERNED_BLOCK,
    MB64_MAT_HMC_SLAB,
    MB64_MAT_RHR_BLOCK,
    MB64_MAT_GRANITE_BLOCK,
    MB64_MAT_C_STONESIDE,
    MB64_MAT_C_PILLAR,
    MB64_MAT_BBH_PILLAR,
    MB64_MAT_RHR_PILLAR,

    MB64_MATLIST_CUTSTONE_END,

    // Wood
    MB64_MAT_WOOD = MB64_MATLIST_CUTSTONE_END,
    MB64_MAT_BBH_WOOD_FLOOR,
    MB64_MAT_BBH_WOOD_WALL,
    MB64_MAT_C_WOOD,
    MB64_MAT_JRB_WOOD,
    MB64_MAT_JRB_SHIPSIDE,
    MB64_MAT_JRB_SHIPTOP,
    MB64_MAT_BBH_HAUNTED_PLANKS,
    MB64_MAT_BBH_ROOF,
    MB64_MAT_SOLID_WOOD,
    MB64_MAT_RHR_WOOD,

    MB64_MATLIST_WOOD_END,

    // Metal
    MB64_MAT_BBH_METAL = MB64_MATLIST_WOOD_END,
    MB64_MAT_JRB_METALSIDE,
    MB64_MAT_JRB_METAL,
    MB64_MAT_C_BASEMENTWALL,
    MB64_MAT_DESERT_TILES2,
    MB64_MAT_VP_RUSTYBLOCK,

    MB64_MATLIST_METAL_END,

    // Buildings
    MB64_MAT_C_CARPET = MB64_MATLIST_METAL_END,
    MB64_MAT_C_WALL,
    MB64_MAT_ROOF,
    MB64_MAT_C_ROOF,
    MB64_MAT_SNOW_ROOF,
    MB64_MAT_BBH_WINDOW,
    MB64_MAT_HMC_LIGHT,
    MB64_MAT_VP_CAUTION,
    MB64_MAT_RR_BLOCKS,
    MB64_MAT_STUDDED_TILE,
    MB64_MAT_TTC_BLOCK,
    MB64_MAT_TTC_SIDE,
    MB64_MAT_TTC_WALL,
    MB64_MAT_FLOWERS,

    MB64_MATLIST_BUILDING_END,

    // Hazards
    MB64_MAT_LAVA = MB64_MATLIST_BUILDING_END,
    MB64_MAT_LAVA_OLD,
    MB64_MAT_SERVER_ACID,
    MB64_MAT_BURNING_ICE,
    MB64_MAT_QUICKSAND,
    MB64_MAT_DESERT_SLOWSAND,
    MB64_MAT_VP_VOID,

    MB64_MATLIST_HAZARD_END,
    
    // Transparent
    MB64_MAT_RHR_MESH = MB64_MATLIST_HAZARD_END,
    MB64_MAT_VP_MESH,
    MB64_MAT_HMC_MESH,
    MB64_MAT_BBH_MESH,
    MB64_MAT_PINK_MESH,
    MB64_MAT_TTC_MESH,
    MB64_MAT_ICE,
    MB64_MAT_CRYSTAL,
    MB64_MAT_VP_SCREEN,

    MB64_MATLIST_END,

    // Retro
    MB64_MAT_RETRO_GROUND = MB64_MATLIST_END,
    MB64_MAT_RETRO_BRICKS,
    MB64_MAT_RETRO_TREETOP,
    MB64_MAT_RETRO_TREEPLAT,
    MB64_MAT_RETRO_BLOCK,
    MB64_MAT_RETRO_BLUEGROUND,
    MB64_MAT_RETRO_BLUEBRICKS,
    MB64_MAT_RETRO_BLUEBLOCK,
    MB64_MAT_RETRO_WHITEBRICK,
    MB64_MAT_RETRO_LAVA,
    MB64_MAT_RETRO_UNDERWATERGROUND,

    // Minecraft
    MB64_MAT_MC_DIRT,
    MB64_MAT_MC_GRASS,
    MB64_MAT_MC_COBBLESTONE,
    MB64_MAT_MC_STONE,
    MB64_MAT_MC_OAK_LOG_TOP,
    MB64_MAT_MC_OAK_LOG_SIDE,
    MB64_MAT_MC_OAK_LEAVES,
    MB64_MAT_MC_WOOD_PLANKS,
    MB64_MAT_MC_SAND,
    MB64_MAT_MC_BRICKS,
    MB64_MAT_MC_LAVA,
    MB64_MAT_MC_FLOWING_LAVA,
    MB64_MAT_MC_GLASS,
};

enum {
    OBJECT_TYPE_SETTINGS,
    OBJECT_TYPE_1, // empty, used to be for screenshot
    OBJECT_TYPE_STAR,
    OBJECT_TYPE_RED_COIN_STAR,
    OBJECT_TYPE_GOOMBA,
    OBJECT_TYPE_BIG_GOOMBA,
    OBJECT_TYPE_TINY_GOOMBA,
    OBJECT_TYPE_PIRANHA_PLANT,
    OBJECT_TYPE_BIG_PIRANHA_PLANT,
    OBJECT_TYPE_TINY_PIRANHA_PLANT,
    OBJECT_TYPE_KOOPA,
    OBJECT_TYPE_COIN,
    OBJECT_TYPE_GREEN_COIN,
    OBJECT_TYPE_RED_COIN,
    OBJECT_TYPE_BLUE_COIN,
    OBJECT_TYPE_BLUE_COIN_SWITCH,
    OBJECT_TYPE_NOTEBLOCK,
    OBJECT_TYPE_BOBOMB,
    OBJECT_TYPE_CHUCKYA,
    OBJECT_TYPE_BULLY,
    OBJECT_TYPE_CHILL_BULLY,
    OBJECT_TYPE_BULLET_BILL,
    OBJECT_TYPE_HEAVE_HO,
    OBJECT_TYPE_MOTOS,
    OBJECT_TYPE_TREE,
    OBJECT_TYPE_EXCL_BOX,
    OBJECT_TYPE_MARIO_SPAWN,
    OBJECT_TYPE_REX,
    OBJECT_TYPE_PODOBOO,
    OBJECT_TYPE_CRABLET,
    OBJECT_TYPE_HAMMER_BRO,
    OBJECT_TYPE_FIRE_BRO,
    OBJECT_TYPE_CHICKEN,
    OBJECT_TYPE_PHANTASM,
    OBJECT_TYPE_WARP_PIPE,
    OBJECT_TYPE_BADGE,
    OBJECT_TYPE_KING_BOBOMB,
    OBJECT_TYPE_KING_WHOMP,
    OBJECT_TYPE_BIG_BOO,
    OBJECT_TYPE_BIG_BULLY,
    OBJECT_TYPE_BIG_CHILL_BULLY,
    OBJECT_TYPE_WIGGLER,
    OBJECT_TYPE_BOWSER,
    OBJECT_TYPE_PLATFORM_TRACK,
    OBJECT_TYPE_PLATFORM_LOOPING,
    OBJECT_TYPE_BOWLING_BALL,
    OBJECT_TYPE_KOOPA_THE_QUICK,
    OBJECT_TYPE_PURPLE_SWITCH,
    OBJECT_TYPE_TIMED_BOX,
    OBJECT_TYPE_RECOVERY_HEART,
    OBJECT_TYPE_TEST_MARIO,// Fake type, used for the Test mario preview
    OBJECT_TYPE_THWOMP,
    OBJECT_TYPE_WHOMP,
    OBJECT_TYPE_GRINDEL,
    OBJECT_TYPE_LAKITU,
    OBJECT_TYPE_FLY_GUY,
    OBJECT_TYPE_SNUFIT,
    OBJECT_TYPE_AMP,
    OBJECT_TYPE_BOO,
    OBJECT_TYPE_MR_I,
    OBJECT_TYPE_SCUTTLEBUG,
    OBJECT_TYPE_BOWSER_BOMB,
    OBJECT_TYPE_FIRE_SPINNER,
    OBJECT_TYPE_COIN_FORMATION,
    OBJECT_TYPE_RED_FLAME,
    OBJECT_TYPE_BLUE_FLAME,
    OBJECT_TYPE_FIRE_SPITTER,
    OBJECT_TYPE_FLAMETHROWER,
    OBJECT_TYPE_SPINDRIFT,
    OBJECT_TYPE_MR_BLIZZARD,
    OBJECT_TYPE_MONEYBAG,
    OBJECT_TYPE_SKEETER,
    OBJECT_TYPE_POKEY,
    OBJECT_TYPE_BBOX_SMALL,
    OBJECT_TYPE_BBOX_NORMAL,
    OBJECT_TYPE_BBOX_CRAZY,
    OBJECT_TYPE_DIAMOND,
    OBJECT_TYPE_SIGN,
    OBJECT_TYPE_BUDDY,
    OBJECT_TYPE_BUTTON,
    OBJECT_TYPE_ON_OFF_BLOCK,
    OBJECT_TYPE_WOODPLAT,
    OBJECT_TYPE_RFBOX,
    OBJECT_TYPE_CULL_PREVIEW, // also fake type
    OBJECT_TYPE_SHOWRUNNER,
    OBJECT_TYPE_CROWBAR,
    OBJECT_TYPE_MASK,
    OBJECT_TYPE_TOAD,
    OBJECT_TYPE_TUXIE,
    OBJECT_TYPE_UKIKI,
    OBJECT_TYPE_MOLEMAN,
    OBJECT_TYPE_COBIE,
    OBJECT_TYPE_CONVEYOR,
    OBJECT_TYPE_TIMEDBLOCK,
    OBJECT_TYPE_TRIGGER,
    OBJECT_TYPE_TRIGGER_STAR,
};

enum {
    MB64_BUTTON_SETTINGS,
    MB64_BUTTON_TEST,
    MB64_BUTTON_TERRAIN,
    MB64_BUTTON_SLOPE,
    MB64_BUTTON_TROLL,
    MB64_BUTTON_STAR,
    MB64_BUTTON_GOOMBA,
    MB64_BUTTON_PIRANHA,
    MB64_BUTTON_KOOPA,
    MB64_BUTTON_COIN,
    MB64_BUTTON_BLANK,
    MB64_BUTTON_GCOIN,
    MB64_BUTTON_CORNER,
    MB64_BUTTON_ICORNER,
    MB64_BUTTON_RCOIN,
    MB64_BUTTON_BCOIN,
    MB64_BUTTON_NOTEBLOCK,
    MB64_BUTTON_CULL,
    MB64_BUTTON_BOBOMB,
    MB64_BUTTON_CHUCKYA,
    MB64_BUTTON_BULLY,
    MB64_BUTTON_BULLET,
    MB64_BUTTON_HEAVEHO,
    MB64_BUTTON_MOTOS,
    MB64_BUTTON_TREE,
    MB64_BUTTON_EXCLA,
    MB64_BUTTON_SPAWN,
    MB64_BUTTON_REX,
    MB64_BUTTON_PODOBOO,
    MB64_BUTTON_CRABLET,
    MB64_BUTTON_HAMMER_BRO,
    MB64_BUTTON_CHICKEN,
    MB64_BUTTON_PHANTASM,
    MB64_BUTTON_PIPE,
    MB64_BUTTON_BADGE,
    MB64_BUTTON_WATER,
    MB64_BUTTON_FENCE,
    MB64_BUTTON_KING_BOBOMB,
    MB64_BUTTON_WIGGLER,
    MB64_BUTTON_BOWSER,
    MB64_BUTTON_MPLAT,
    MB64_BUTTON_BBALL,
    MB64_BUTTON_KTQ,
    MB64_BUTTON_SSLOPE,
    MB64_BUTTON_SLAB,
    MB64_BUTTON_PURPLE_SWITCH,
    MB64_BUTTON_TIMED_BOX,
    MB64_BUTTON_HEART,
    MB64_BUTTON_FORMATION,
    MB64_BUTTON_VSLAB,
    MB64_BUTTON_SCORNER,
    MB64_BUTTON_UGENTLE,
    MB64_BUTTON_LGENTLE,
    MB64_BUTTON_BARS,
    MB64_BUTTON_THWOMP,
    MB64_BUTTON_WHOMP,
    MB64_BUTTON_POLE,
    MB64_BUTTON_VEXCLA,
    MB64_BUTTON_LAKITU,
    MB64_BUTTON_FLYGUY,
    MB64_BUTTON_SNUFIT,
    MB64_BUTTON_AMP,
    MB64_BUTTON_BOO,
    MB64_BUTTON_MR_I,
    MB64_BUTTON_SCUTTLEBUG,
    MB64_BUTTON_SPINDRIFT,
    MB64_BUTTON_BLIZZARD,
    MB64_BUTTON_MONEYBAG,
    MB64_BUTTON_SKEETER,
    MB64_BUTTON_POKEY,
    MB64_BUTTON_MINE,
    MB64_BUTTON_FIRE,
    MB64_BUTTON_FLAMETHROWER,
    MB64_BUTTON_FIRE_SPITTER,
    MB64_BUTTON_FIRE_SPINNER,
    MB64_BUTTON_BREAKABLE,
    MB64_BUTTON_SMALL_BOX,
    MB64_BUTTON_DIAMOND,
    MB64_BUTTON_NPC,
    MB64_BUTTON_NPCCM,
    MB64_BUTTON_BUTTON,
    MB64_BUTTON_BLOCK,
    MB64_BUTTON_WOODPLAT,
    MB64_BUTTON_RFBOX,
    MB64_BUTTON_SHOWRUN,
    MB64_BUTTON_POWER,
    MB64_BUTTON_CONVEYOR,
    MB64_BUTTON_ISCORNER,
    MB64_BUTTON_TRIGGER,

    MB64_BUTTON_COUNT,
};


extern f32 mb64_camera_zoom_table[][2];
extern void *mb64_theme_segments[][4];
extern LevelScript *mb64_theme_model_scripts[];

extern void *slope_decal_below_surfs[];
extern struct mb64_terrain_poly mb64_terrain_fullblock_quads[];
extern struct mb64_terrain mb64_terrain_fullblock;
extern struct mb64_terrain_poly mb64_terrain_bars_connected_quads[];
extern struct mb64_terrain_poly mb64_terrain_bars_unconnected_quad[];
extern struct mb64_terrain_poly mb64_terrain_bars_center_quads[];
extern struct mb64_terrain mb64_terrain_pole;
extern struct mb64_terrain mb64_terrain_fence;
extern struct mb64_terrain mb64_terrain_fence_col;
extern struct mb64_terrain_poly *mb64_terrain_water_quadlists[];
extern struct mb64_terrain_info mb64_terrain_info_list[];

extern u8 mb64_matlist[];
extern struct mb64_material mb64_mat_table[];
extern u32 mb64_render_mode_table[];
extern struct mb64_theme mb64_theme_table[];
extern struct mb64_custom_theme mb64_default_custom;
extern struct mb64_custom_theme mb64_curr_custom_theme;

extern Gfx *mb64_fence_texs[];
extern Gfx *mb64_bar_texs[][2];
extern Gfx *mb64_water_texs[];

extern struct ExclamationBoxContents sExclamationBoxContents_btcm[];
extern struct ExclamationBoxContents sExclamationBoxContents_vanilla[];
extern struct mb64_object_info mb64_object_type_list[];
extern struct mb64_ui_button_type mb64_ui_buttons[];

extern u8 mb64_toolbox_btcm[18 * 5];
extern u8 mb64_toolbox_vanilla[18 * 5];
extern u8 seq_musicmenu_array[];
extern u8 mb64_envfx_table[];
extern u8 mb64_boundary_table[];
extern u8 *mb64_skybox_table[];

extern struct mb64_settings_button mb64_settings_mat_selector[];
extern struct mb64_settings_button mb64_settings_other_selectors[];

extern struct mb64_template mb64_templates[];
extern u8 mb64_text_colors[][3];

extern struct ImbueData imbue_table[];
