#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bbh/header.h"

#include "levels/bbh/staircase_step/geo.inc.c"
#include "levels/bbh/tilting_trap_platform/geo.inc.c"
#include "levels/bbh/tumbling_platform_far/geo.inc.c"
#include "levels/bbh/tumbling_platform_near/geo.inc.c"
#include "levels/bbh/moving_bookshelf/geo.inc.c"
#include "levels/bbh/mesh_elevator/geo.inc.c"
#include "levels/bbh/merry_go_round/geo.inc.c"
#include "levels/bbh/coffin/geo.inc.c"
#include "levels/bbh/areas/1/geo.inc.c"
#include "levels/bbh/geo.inc.c"

#include "levels/bbh/barell/geo.inc.c"
#include "levels/bbh/iceberg/geo.inc.c"
#include "levels/bbh/ship_elevator/geo.inc.c"
#include "levels/bbh/ship_elevator_rope/geo.inc.c"
#include "levels/bbh/ship_elevator_pulley/geo.inc.c"
#include "levels/bbh/GhostBoard/geo.inc.c"
#include "levels/bbh/iceberg_LOD/geo.inc.c"
#include "levels/bbh/lightning/geo.inc.c"
#include "levels/bbh/boomate/geo.inc.c"
#include "levels/bbh/GhostGate/geo.inc.c"
#include "levels/bbh/GhostKey/geo.inc.c"
#include "levels/bbh/Goblet/geo.inc.c"
#include "levels/bbh/BooCaptain/geo.inc.c"
#include "levels/bbh/Evilship/geo.inc.c"
#include "levels/bbh/puddle/geo.inc.c"
#include "levels/bbh/puddlebomb/geo.inc.c"
#include "levels/bbh/boocannon/geo.inc.c"