#include "levels/bbh/area_1/collision.inc.c"
#include "levels/bbh/area_1/macro.inc.c"
#include "levels/bbh/area_1/spline.inc.c"
#include "levels/bbh/area_2/collision.inc.c"
#include "levels/bbh/area_2/macro.inc.c"
#include "levels/bbh/area_2/spline.inc.c"
#include "levels/bbh/model.inc.c"
