extern const GeoLayout rfbox_geo[];
extern Lights1 rfbox_corkreinforced_lights;
extern u8 rfbox_output_ci8[];
extern u8 rfbox_output_ci8_pal_rgba16[];
extern Vtx rfbox_blaster_004_mesh_layer_1_vtx_0[24];
extern Gfx rfbox_blaster_004_mesh_layer_1_tri_0[];
extern Gfx mat_rfbox_corkreinforced[];
extern Gfx mat_revert_rfbox_corkreinforced[];
extern Gfx rfbox_blaster_004_mesh_layer_1[];
extern Gfx rfbox_material_revert_render_settings[];
