extern const GeoLayout cosmic_missile_geo[];
extern Lights1 cosmic_missile_White_lights;
extern u8 cosmic_missile_small_metal_rgba16[];
extern Vtx cosmic_missile_Cylinder_023_mesh_layer_1_vtx_cull[8];
extern Vtx cosmic_missile_Cylinder_023_mesh_layer_1_vtx_0[70];
extern Gfx cosmic_missile_Cylinder_023_mesh_layer_1_tri_0[];
extern Vtx cosmic_missile_Cylinder_023_mesh_layer_1_vtx_1[144];
extern Gfx cosmic_missile_Cylinder_023_mesh_layer_1_tri_1[];
extern Gfx mat_cosmic_missile_White[];
extern Gfx mat_cosmic_missile_cosmic[];
extern Gfx mat_revert_cosmic_missile_cosmic[];
extern Gfx cosmic_missile_Cylinder_023_mesh_layer_1[];
extern Gfx cosmic_missile_material_revert_render_settings[];
