extern const GeoLayout geo_boomate[];
extern Lights1 boomate_face_lights;
extern Lights1 boomate_hat_lights;
extern u8 boomate_eye_ci8[];
extern u8 boomate_eye_ci8_pal_rgba16[];
extern u8 boomate_hat_ci4[];
extern u8 boomate_hat_ci4_pal_rgba16[];
extern Vtx boomate_boo_mesh_layer_5_vtx_0[86];
extern Gfx boomate_boo_mesh_layer_5_tri_0[];
extern Vtx boomate_boo_mesh_layer_1_vtx_0[30];
extern Gfx boomate_boo_mesh_layer_1_tri_0[];
extern Gfx mat_boomate_face[];
extern Gfx mat_revert_boomate_face[];
extern Gfx mat_boomate_hat[];
extern Gfx mat_revert_boomate_hat[];
extern Gfx boomate_boo_mesh_layer_5[];
extern Gfx boomate_boo_mesh_layer_1[];
extern Gfx boomate_material_revert_render_settings[];
