extern const GeoLayout sr_spike_geo[];
extern Lights1 sr_spike_Stone_lights;
extern u8 sr_spike_Concrete_ci4[];
extern u8 sr_spike_Concrete_ci4_pal_rgba16[];
extern Vtx sr_spike_Cone_mesh_layer_1_vtx_cull[8];
extern Vtx sr_spike_Cone_mesh_layer_1_vtx_0[9];
extern Gfx sr_spike_Cone_mesh_layer_1_tri_0[];
extern Gfx mat_sr_spike_Stone[];
extern Gfx mat_revert_sr_spike_Stone[];
extern Gfx sr_spike_Cone_mesh_layer_1[];
extern Gfx sr_spike_material_revert_render_settings[];
