extern const GeoLayout curtaincall_geo[];
extern Lights1 curtaincall_Curtain_lights;
extern u8 curtaincall_Curtain_ia8[];
extern Vtx curtaincall_Cube_007_mesh_layer_4_vtx_cull[8];
extern Vtx curtaincall_Cube_007_mesh_layer_4_vtx_0[14];
extern Gfx curtaincall_Cube_007_mesh_layer_4_tri_0[];
extern Gfx mat_curtaincall_Curtain[];
extern Gfx mat_revert_curtaincall_Curtain[];
extern Gfx curtaincall_Cube_007_mesh_layer_4[];
extern Gfx curtaincall_material_revert_render_settings[];
