extern const GeoLayout bobomb_Eyes_blinking[];
extern const GeoLayout black_bobomb_geo[];
extern const GeoLayout bobomb_buddy_geo[];
extern Lights1 bobomb_hat_lights;
extern Lights1 bobomb_feet_lights;
extern u8 bobomb_bob_omb_left_side_rgba16_rgba16[];
extern u8 bobomb_bob_omb_right_side_rgba16_rgba16[];
extern u8 bobomb_bob_omb_buddy_left_side_rgba16_rgba16[];
extern u8 bobomb_bob_omb_buddy_right_side_rgba16_rgba16[];
extern u8 bobomb_bob_omb_eyes_rgba16_rgba16[];
extern u8 bobomb_bob_omb_eyes_blink_rgba16_rgba16[];
extern Vtx bobomb_root_mesh_layer_1_vtx_0[34];
extern Vtx bobomb_body_mesh_layer_4_vtx_0[4];
extern Vtx bobomb_body_mesh_layer_4_vtx_1[4];
extern Vtx bobomb_idle_eyes_mesh_layer_4_vtx_0[6];
extern Vtx bobomb_eyes_blinking_switch_option_001_offset_mesh_layer_4_vtx_0[6];
extern Vtx bobomb_left_foot_mesh_layer_1_vtx_0[16];
extern Vtx bobomb_right_foot_mesh_layer_1_vtx_0[16];
extern Gfx bobomb_root_mesh_layer_1[];
extern Gfx black_bobomb_body_mesh_layer_4[];
extern Gfx bobomb_buddy_body_mesh_layer_4[];
extern Gfx bobomb_idle_eyes_mesh_layer_4[];
extern Gfx bobomb_eyes_blinking_switch_option_Eyes_blinking_mesh_layer_4[];
extern Gfx bobomb_left_foot_mesh_layer_1[];
extern Gfx bobomb_right_foot_mesh_layer_1[];
extern Gfx bobomb_material_revert_render_settings[];
