extern const GeoLayout retrotoad_geo[];
extern u8 retrotoad_Toad_ci4[];
extern u8 retrotoad_Toad_ci4_pal_rgba16[];
extern Vtx retrotoad_Plane_003_mesh_layer_4_vtx_cull[8];
extern Vtx retrotoad_Plane_003_mesh_layer_4_vtx_0[4];
extern Gfx retrotoad_Plane_003_mesh_layer_4_tri_0[];
extern Gfx mat_retrotoad_toad[];
extern Gfx mat_revert_retrotoad_toad[];
extern Gfx retrotoad_Plane_003_mesh_layer_4[];
extern Gfx retrotoad_material_revert_render_settings[];
