extern const GeoLayout imbuet_geo[];
extern Vtx imbuet_imbue_trigger_mesh_layer_7_vtx_cull[8];
extern Vtx imbuet_imbue_trigger_mesh_layer_7_vtx_0[32];
extern Gfx imbuet_imbue_trigger_mesh_layer_7_tri_0[];
extern Vtx imbuet_imbue_trigger_mesh_layer_7_vtx_1[16];
extern Gfx imbuet_imbue_trigger_mesh_layer_7_tri_1[];
extern Gfx mat_imbuet_noz_black[];
extern Gfx mat_revert_imbuet_noz_black[];
extern Gfx mat_imbuet_noz_orange[];
extern Gfx mat_revert_imbuet_noz_orange[];
extern Gfx imbuet_imbue_trigger_mesh_layer_7[];
