extern const GeoLayout onoffswitch_000_switch_opt1[];
extern const GeoLayout onoffswitch_geo[];
extern Lights1 onoffswitch_redswitch_lights;
extern Lights1 onoffswitch_blueswitch_lights;
extern u8 onoffswitch_redswitch_ci8[];
extern u8 onoffswitch_redswitch_ci8_pal_rgba16[];
extern u8 onoffswitch_blueswitch_ci8[];
extern u8 onoffswitch_blueswitch_ci8_pal_rgba16[];
extern Vtx onoffswitch_000_displaylist_mesh_layer_1_vtx_0[40];
extern Gfx onoffswitch_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_onoffswitch_redswitch[];
extern Gfx mat_revert_onoffswitch_redswitch[];
extern Gfx mat_onoffswitch_blueswitch[];
extern Gfx mat_revert_onoffswitch_blueswitch[];
extern Gfx onoffswitch_000_displaylist_mesh_layer_1[];
extern Gfx onoffswitch_000_displaylist_mesh_layer_1_mat_override_blueswitch_0[];
extern Gfx onoffswitch_material_revert_render_settings[];
