extern const GeoLayout onoffblock1_000_switch_opt1[];
extern const GeoLayout onoffblock1_000_switch_opt2[];
extern const GeoLayout onoffblock1_geo[];
extern Lights1 onoffblock1_redblock_lights;
extern Lights1 onoffblock1_blueblock_lights;
extern Lights1 onoffblock1_yellowblock_lights;
extern u8 onoffblock1_redbox_ci8[];
extern u8 onoffblock1_redbox_ci8_pal_rgba16[];
extern u8 onoffblock1_bluebox_ci8[];
extern u8 onoffblock1_bluebox_ci8_pal_rgba16[];
extern u8 onoffblock1_yellowbox_ci8[];
extern u8 onoffblock1_yellowbox_ci8_pal_rgba16[];
extern Vtx onoffblock1_000_displaylist_mesh_layer_1_vtx_0[158];
extern Gfx onoffblock1_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_onoffblock1_redblock[];
extern Gfx mat_revert_onoffblock1_redblock[];
extern Gfx mat_onoffblock1_blueblock[];
extern Gfx mat_revert_onoffblock1_blueblock[];
extern Gfx mat_onoffblock1_yellowblock[];
extern Gfx mat_revert_onoffblock1_yellowblock[];
extern Gfx onoffblock1_000_displaylist_mesh_layer_1[];
extern Gfx onoffblock1_000_displaylist_mesh_layer_1_mat_override_blueblock_0[];
extern Gfx onoffblock1_000_displaylist_mesh_layer_1_mat_override_yellowblock_1[];
extern Gfx onoffblock1_material_revert_render_settings[];
