extern const GeoLayout movie3_geo[];
extern u8 movie3_Projector_Brick_1_i8[];
extern u8 movie3_Projector_Brick_2_ia8[];
extern Vtx movie3_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx movie3_Cube_mesh_layer_5_vtx_0[101];
extern Gfx movie3_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_movie3_ProjectorBrick_layer5[];
extern Gfx mat_revert_movie3_ProjectorBrick_layer5[];
extern Gfx movie3_Cube_mesh_layer_5[];
extern Gfx movie3_material_revert_render_settings[];
