extern const GeoLayout SS_root1_opt1[];
extern const GeoLayout SS_root1_opt2[];
extern const GeoLayout SS_root1_opt3[];
extern const GeoLayout SS_root1_opt4[];
extern const GeoLayout SS_geo[];
extern u8 SS_SS_None_i8[];
extern u8 SS_SS_Circle_i8[];
extern u8 SS_SS_Square_i8[];
extern u8 SS_SS_Triangle_i8[];
extern u8 SS_SS_Star_i8[];
extern Vtx SS_boner1_mesh_layer_1_vtx_0[4];
extern Gfx SS_boner1_mesh_layer_1_tri_0[];
extern Gfx mat_SS_SS_Dark[];
extern Gfx mat_SS_SS_Circle[];
extern Gfx mat_SS_SS_Square[];
extern Gfx mat_SS_SS_Triangle[];
extern Gfx mat_SS_SS_Star[];
extern Gfx SS_boner1_mesh_layer_1[];
extern Gfx SS_boner1_mesh_layer_1_mat_override_SS_Circle_0[];
extern Gfx SS_boner1_mesh_layer_1_mat_override_SS_Square_1[];
extern Gfx SS_boner1_mesh_layer_1_mat_override_SS_Triangle_2[];
extern Gfx SS_boner1_mesh_layer_1_mat_override_SS_Star_3[];
extern Gfx SS_material_revert_render_settings[];
