extern const GeoLayout t_trap_geo[];
extern Lights1 t_trap_vcolorbricks_lights;
extern Lights1 t_trap_CarpetVcolor_lights;
extern u8 t_trap_HQ_Brick_i8[];
extern u8 t_trap_HQ_Carpet_i8[];
extern Vtx t_trap_Cube_003_mesh_layer_1_vtx_0[20];
extern Gfx t_trap_Cube_003_mesh_layer_1_tri_0[];
extern Vtx t_trap_Cube_003_mesh_layer_1_vtx_1[4];
extern Gfx t_trap_Cube_003_mesh_layer_1_tri_1[];
extern Gfx mat_t_trap_vcolorbricks[];
extern Gfx mat_revert_t_trap_vcolorbricks[];
extern Gfx mat_t_trap_CarpetVcolor[];
extern Gfx mat_revert_t_trap_CarpetVcolor[];
extern Gfx t_trap_Cube_003_mesh_layer_1[];
extern Gfx t_trap_material_revert_render_settings[];
