extern const GeoLayout woodplat_geo[];
extern Lights1 woodplat_woodside_lights;
extern Lights1 woodplat_woodtop_lights;
extern u8 woodplat_woodplatside_ci8[];
extern u8 woodplat_woodplatside_pal_rgba16[];
extern u8 woodplat_woodplattop_ci8[];
extern u8 woodplat_woodplattop_pal_rgba16[];
extern Vtx woodplat_blaster_002_mesh_layer_1_vtx_0[16];
extern Gfx woodplat_blaster_002_mesh_layer_1_tri_0[];
extern Vtx woodplat_blaster_002_mesh_layer_1_vtx_1[8];
extern Gfx woodplat_blaster_002_mesh_layer_1_tri_1[];
extern Gfx mat_woodplat_woodside[];
extern Gfx mat_revert_woodplat_woodside[];
extern Gfx mat_woodplat_woodtop[];
extern Gfx mat_revert_woodplat_woodtop[];
extern Gfx woodplat_blaster_002_mesh_layer_1[];
extern Gfx woodplat_material_revert_render_settings[];
