extern const GeoLayout cobie2_switch_opt1[];
extern const GeoLayout cobie2_switch_opt2[];
extern const GeoLayout cobie2_geo[];
extern Lights1 cobie2_Cobie_Good_lights;
extern Lights1 cobie2_Cobie_Bad_lights;
extern u8 cobie2_Cobie_Good_ci8[];
extern u8 cobie2_Cobie_Good_pal_rgba16[];
extern u8 cobie2_Cobie_Bad_ci8[];
extern u8 cobie2_Cobie_Bad_pal_rgba16[];
extern u8 cobie2_cobie_metal_rgba16[];
extern Vtx cobie2_root_mesh_layer_1_vtx_0[123];
extern Gfx cobie2_root_mesh_layer_1_tri_0[];
extern Vtx cobie2_gun_mesh_layer_1_vtx_0[46];
extern Gfx cobie2_gun_mesh_layer_1_tri_0[];
extern Vtx cobie2_lfoot_mesh_layer_1_vtx_0[14];
extern Gfx cobie2_lfoot_mesh_layer_1_tri_0[];
extern Vtx cobie2_rfoot_mesh_layer_1_vtx_0[14];
extern Gfx cobie2_rfoot_mesh_layer_1_tri_0[];
extern Gfx mat_cobie2_Cobie_Good[];
extern Gfx mat_revert_cobie2_Cobie_Good[];
extern Gfx mat_cobie2_Cobie_Bad[];
extern Gfx mat_revert_cobie2_Cobie_Bad[];
extern Gfx mat_cobie2_Void_001[];
extern Gfx mat_revert_cobie2_Void_001[];
extern Gfx cobie2_root_mesh_layer_1[];
extern Gfx cobie2_root_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie2_root_mesh_layer_1_mat_override_Void_001_1[];
extern Gfx cobie2_gun_mesh_layer_1[];
extern Gfx cobie2_gun_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie2_gun_mesh_layer_1_mat_override_Void_001_1[];
extern Gfx cobie2_lfoot_mesh_layer_1[];
extern Gfx cobie2_lfoot_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie2_lfoot_mesh_layer_1_mat_override_Void_001_1[];
extern Gfx cobie2_rfoot_mesh_layer_1[];
extern Gfx cobie2_rfoot_mesh_layer_1_mat_override_Cobie_Bad_0[];
extern Gfx cobie2_rfoot_mesh_layer_1_mat_override_Void_001_1[];
extern Gfx cobie2_material_revert_render_settings[];
