extern const GeoLayout conv1_ccm_geo[];
extern u8 conv1_ccm_FactoryArrow_ci8[];
extern u8 conv1_ccm_FactoryArrow_ci8_pal_rgba16[];
extern Vtx conv1_ccm_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx conv1_ccm_Circle_mesh_layer_1_vtx_0[64];
extern Gfx conv1_ccm_Circle_mesh_layer_1_tri_0[];
extern Gfx mat_conv1_ccm_Conveyor[];
extern Gfx mat_revert_conv1_ccm_Conveyor[];
extern Gfx conv1_ccm_Circle_mesh_layer_1[];
extern Gfx conv1_ccm_material_revert_render_settings[];
