extern const GeoLayout cursedkey_geo[];
extern u8 cursedkey_CursedKey_ci4[];
extern u8 cursedkey_CursedKey_ci4_pal_rgba16[];
extern Vtx cursedkey_Plane_007_mesh_layer_4_vtx_cull[8];
extern Vtx cursedkey_Plane_007_mesh_layer_4_vtx_0[4];
extern Gfx cursedkey_Plane_007_mesh_layer_4_tri_0[];
extern Gfx mat_cursedkey_f3d_material[];
extern Gfx mat_revert_cursedkey_f3d_material[];
extern Gfx cursedkey_Plane_007_mesh_layer_4[];
extern Gfx cursedkey_material_revert_render_settings[];
