extern const GeoLayout flip_geo[];
extern Lights1 flip_Neon_lights;
extern u8 flip_Neon_i8[];
extern Vtx flip_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx flip_Cube_003_mesh_layer_1_vtx_0[56];
extern Gfx flip_Cube_003_mesh_layer_1_tri_0[];
extern Gfx mat_flip_Neon[];
extern Gfx mat_revert_flip_Neon[];
extern Gfx flip_Cube_003_mesh_layer_1[];
extern Gfx flip_material_revert_render_settings[];
